### ISSUE TITLE
addons:rt:hasconnection(ship). and addons:rt:haslocalcontrol(ship). not working

### ISSUE THREAD

**Issue by blnk2007** [KSP-KOS/KOS#1397] opened 2016-02-03 17:56 UTC
As of the latest update and having the latest remotetech installed and rt integration on, addons:rt:hasconnection(ship) and addons:rt:haslocalcontrol(ship) both return false even with a connection and local control.

**Comment by gisikw** [comment] 2016-02-03 18:28
Can you specify which versions you're using? I'm not able to reproduce the issue with kOS 0.18.2 and RemoteTech 1.6.8.

**Comment by blnk2007** [comment] 2016-02-03 18:31
remotetech 1.6.9 and the latest kos release.

**Comment by gisikw** [comment] 2016-02-03 18:37
Whoops, sorry, typo on my part. Yehp, can't reproduce the issues under 1.6.9 and 0.18.2. Can you provide the full script that's failing? There may be some other issue you're encountering.

**Comment by blnk2007** [comment] 2016-02-03 18:46
I tried it simply as those commands at various times throughout launch. I did install seti-ctt and seti-rebalance mods. maybe they caused the issue. I'll uninstall them and see if they caused the problem.

**Comment by blnk2007** [comment] 2016-02-03 18:49
set ship:control:pilotmainthrottle to 0.

function has_file {
  parameter name.
  parameter vol.

  switch to vol.
  list files in allfiles.
  for file in allfiles {
    if file:name = name {
      switch to 1.
      return true.
    }
  }
  switch to 1.
  return false.
}

function download {
  parameter name.

  if has_file(name, 1) {
    delete name.
  }
  if has_file(name, 0) {
    copy name from 0.
  }
}

function upload {
  parameter name.

  if has_file(name, 1) {
    delete name.
  }
  if has_file(name, 0) {
    copy name from 0.
  }
}

// bootup
set updatescript to ship:name + ".update.ks".

if addons:rt:hasconnection(ship) or ship:status ="prelaunch" {
  if has_file(updatescript, 0) {
    download(updatescript).
    switch to 0. delete updatescript. switch to 1.
    if has_file("update.ks", 1) {
      delete update.ks.
    }
    rename updatescript to "update.ks".
    run update.ks.
    delete update.ks.
  }
}

if has_file("startup.ks", 1) {
  run startup.ks.
}
else {
  wait until addons:rt:hasconnection(ship) or ship:status = "prelaunch".
  wait 10.
  reboot.
}

**Comment by hvacengi** [comment] 2016-02-03 18:55
Do you have the config flag for remote tech set to true?  (`set config:rt to true.`)

**Comment by gisikw** [comment] 2016-02-03 18:56
Hey, I recognize that boot script ;)

This probably won't be related, but looking at this line:
`if addons:rt:hasconnection(ship) or ship:status ="prelaunch" {`

You probably want that to be `and` rather than `or`, as it's possible the ship's status will be noted before RT detects the connection, which would cause crashes.

**Comment by hvacengi** [comment] 2016-02-03 18:59
I'm not sure of the sequencing, but you might also want to add a line at the top:
```
wait until ship:unpacked.
```
That way the script will not execute before the vessel is fully rendered.  It is possible to have a script execute before the Scene itself fully loads (this bug is known and will be fixed)

**Comment by blnk2007** [comment] 2016-02-03 19:03
Yes, addons:rt:available comes back as true. As far as the boot script goes I had to add or `ship:status ="prelaunch" ` otherwise the bootscript would just hang because it never got a connection.

**Comment by blnk2007** [comment] 2016-02-03 20:04
uninstalling seti stuff didn't work. I am on linux 64bit if that matters.

**Comment by blnk2007** [comment] 2016-02-03 20:25
Just wanted to clarify with everyone. This is in a manned capsule. Everything still works correctly with probes.

**Comment by tomekpiotrowski** [comment] 2016-02-03 20:28
Do you have a signal processor/probe on board? RemoteTech needs them to work even in manned vessels.

**Comment by gisikw** [comment] 2016-02-03 20:29
Ah! `hasconnection` doesn't return true for local control. It's explicitly checking for a connection to KSC or a command center. For that, you'll want to use `haslocalcontrol`. Though presumably, since you're relying on the archive volume, you actually do want a remote connection.

**Comment by blnk2007** [comment] 2016-02-03 20:30
'haslocalcontrol(ship)' also returns false.

**Comment by gisikw** [comment] 2016-02-03 20:34
Good catch, @tomekpiotrowski!

**Comment by blnk2007** [comment] 2016-02-03 20:36
@tomekpiotrowski This solved the problem! I guess even manned capsules need a signal processor/probe. I didn't know that.

**Comment by blnk2007** [comment] 2016-02-03 20:38
What's the reason kOS processors aren't also signal processors?

**Comment by tomekpiotrowski** [comment] 2016-02-03 20:39
That's something that would have to be discussed. #1305 is related.

**Comment by tomekpiotrowski** [comment] 2016-02-03 20:52
I'll close this as the main issue is solved. Related discussions will follow in other issues.

**Closed by tomekpiotrowski** 2016-02-03 20:52 UTC
