### ISSUE TITLE
"failed to convert parameters" calling irservo:moveto()

### ISSUE THREAD

**Issue by allmhuran** [KSP-KOS/KOS#1509] opened 2016-03-05 18:59 UTC
![ftcp](https://cloud.githubusercontent.com/assets/7334974/13549729/618c0d16-e360-11e5-9233-430a92b0ed34.png)

When calling irservo:moveto(), an error of the form "failed to convert parameters" occurs, related to the speedMulti parameter. Image attached.

**Comment by hvacengi** [comment] 2016-03-05 19:01
Duplicate of #1503, already fixed and it will be in the update which we're working on pushing now.

**Closed by hvacengi** 2016-03-05 19:01 UTC
Labels: duplicate

**Comment by allmhuran** [comment] 2016-03-05 19:15
Haha, no offense taken, I only searched for "convert" and "moveto" before submitting this and didn't recognise the existing one as related. Nice work as always.
