### ISSUE TITLE
Round number floats not treated as ints for volume number. i.e. switch to 0.00. fails.

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#897] opened 2015-04-25 09:16 UTC
![screenshot1](https://cloud.githubusercontent.com/assets/11031560/7332354/413e538a-eb44-11e4-812f-b7df0bcb3ae2.png)
P.S. encountered it when using `mod()` on the volume number.

**Comment by abenkovskii** [comment] 2015-04-25 16:26
@erendrake Switch does accept variables (integers and probably strings). It doesn't accept floats.
![screenshot2](https://cloud.githubusercontent.com/assets/11031560/7333672/052cfad0-eb81-11e4-820a-e85ffd55e1cf.png)

**Comment by erendrake** [comment] 2015-04-25 16:43
Ah that should be much simpler to fix. Thank you for the clarification

**Comment by abenkovskii** [comment] 2015-04-25 16:46
Not at all.

**Comment by Dunbaratu** [comment] 2015-04-25 16:54
Why on earth is it a bug that it can't switch to volume number 0.00001 ?   That looks pretty correct to me.

**Comment by abenkovskii** [comment] 2015-04-25 16:56
Because you can't switch to the volume `mod(7, vol_list:length)`

**Comment by Dunbaratu** [comment] 2015-04-25 17:08
``switch to round(i,0).``
There is no such thing as volume 0.00001.  That is correct that you can't switch to it.  It's only a problem if it won't let you switch to, say, 0.00000 or 1.00000 - THEN it would be a problem because floats and ints are meant to be interchangeable WHEN and only when the float has no fractional component.

**Comment by abenkovskii** [comment] 2015-04-25 17:14
@Dunbaratu Need a "real" example? Here you are:
![screenshot3](https://cloud.githubusercontent.com/assets/11031560/7333876/75747f56-eb87-11e4-904e-612e451d52ca.png)
P.S. some_list[0.2] works

**Comment by Dunbaratu** [comment] 2015-04-25 17:28
Then it is what I said with:

> It's only a problem if it won't let you switch to, say, 0.00000 or 1.00000

Using a weird example of 0.00001, where it's *correct* that it doesn't allow it, doesn't illustrate the problem.  The problem is that every time you push a float to the stack it is *supposed* to be transforming it into an int if its a round number.  That is clearly not happening here.

What should NOT be happening is that we sprinkle special case code everywhere in the mod to sanitize the integer-expecting inputs in those places where integers are expected.  The transformation of round number floats into integers should be happening universally in one place.

some_list[0.2] shouldn't work.  If it does then that's a bug.  What *should* work is some_list[0.0000] or some_list[2.0000].  You can use a float in place of an integer, but only if the float really IS a round number.

**Comment by abenkovskii** [comment] 2015-04-25 17:32
Yes I think your way is better.

**Comment by Dunbaratu** [comment] 2015-04-25 17:38
Changed the title to mention the actual problem happening.

**Comment by erendrake** [comment] 2015-04-25 17:49
And that is why I marked it as an enhancement. This is a nice to have kind of thing. If we want it at all.

**Comment by Dunbaratu** [comment] 2015-04-25 17:52
Once the actual problem got nailed down, I think it is a bug, actually.  We're supposed to be treating all round numbers as being interchangeable with integers, precisely because users can't cast.  So when they get handed a number from the API that is floating point when they needed an integer, they can't do anything about it.

**Comment by abenkovskii** [comment] 2015-05-09 12:59
@Dunbaratu Should it be inserted here: https://github.com/KSP-KOS/KOS/blob/ade0aa64e08b68a0a2dd1f766a6a53d781391aff/src/kOS/Execution/Stack.cs#L15 or thre is more sutable space for it?

**Comment by abenkovskii** [comment] 2015-05-09 15:52
I'm going to try implementing it. Expect a PR soon.

**Closed** 2015-05-13 17:30 UTC
Labels: enhancement
