### ISSUE TITLE
EDIT File can't type "r", "s" or "e"

### ISSUE THREAD

**Issue by Rinma** [KSP-KOS/KOS#1969] opened 2017-03-02 18:50 UTC
When I am in the editor to write a file I can't use the keys that are used for actions. When I try to write the word "PRINT" I write "PINT" because the "R" doesn't work.

I play Kerbal Space Program 1.2.2.1622(LinuxPlayer) on an Arch Linux (AntergOS) with Steam.

**Comment by hvacengi** [comment] 2017-03-02 19:16
This is a duplicate of issues #1071 and #1593.  Unity/KSP does something funny on Linux that seems to break text fields.  The hope was that KSP's upgrade to Unity 5 would eliminate the issue, but apparently it has not.  This has not as of yet been a major issue (as most people tend to use external editors anyways).  @Dunbaratu has been looking at an upgrade to our font system which would eventually include a re-write of the editor, but I don't know if that will be ready for the next release.

I'm going to close the issue as a duplicate, so please direct further comments to #1071.

**Closed by hvacengi** 2017-03-02 19:16 UTC
Labels: duplicate
