### ISSUE TITLE
Redeclaration of functions crashes program.

### ISSUE THREAD

**Issue by akrasuski1** [KSP-KOS/KOS#1022] opened 2015-05-16 20:35 UTC
But this only crashes, if they are not in the same file. For example, this (`not_a_bug.ks`) works fine:
```
@lazyglobal off.
function not_crashing{
    print 1.
}
function not_crashing{
    print 1.
}
```
when ran using this command: `run not_a_bug.`

The bug shows up when you run a file multiple times:
```
//bug.ks
@lazyglobal off.
function reproduce{
    print 1.
}
```
and then, in interpreter I type `until false{run bug.}` I'd expect the behaviour to be the same ("Program ended" printed many times), but instead I get this text:
```
Program ended.
Argument is out of range.
Parameter name: index.
At interpreter history, line 22
until false{run bug.}
```

**Comment by abenkovskii** [comment] 2015-05-18 06:00
It's not functions but run command in a loop causes problems:
![screenshot0](https://cloud.githubusercontent.com/assets/11031560/7674979/dd27bec8-fd3a-11e4-9510-652b85ee3020.png)
```
(Filename: C:/buildslave/unity/build/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

kOS: Execution Broken
 
(Filename: C:/buildslave/unity/build/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

kOS: Logger: Argument is out of range.
Parameter name: index
 
(Filename: C:/buildslave/unity/build/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

kOS: Logger:   at System.Collections.Generic.List`1[System.String].get_Item (Int32 index) [0x00000] in <filename unknown>:0 
  at kOS.Screen.Interpreter.GetCommandHistoryAbsolute (Int32 absoluteIndex) [0x00000] in <filename unknown>:0 
  at kOS.KSPLogger.GetSourceLine (System.String filePath, Int32 line) [0x00000] in <filename unknown>:0 
  at kOS.KSPLogger.TraceLog () [0x00000] in <filename unknown>:0 
 
(Filename: C:/buildslave/unity/build/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

kOS: (Cannot Show kOS Error Location - error might really be internal. See kOS devs.)
 
(Filename: C:/buildslave/unity/build/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

System.ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
  at System.Collections.Generic.List`1[System.Object].get_Item (Int32 index) [0x00000] in <filename unknown>:0 
  at kOS.Execution.Stack.Pop () [0x00000] in <filename unknown>:0 
  at kOS.Execution.CPU.PopStack () [0x00000] in <filename unknown>:0 
  at kOS.Execution.CPU.PopValue (Boolean barewordOkay) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Compilation.OpcodePop.Execute (ICpu cpu) [0x00000] in <filename unknown>:0 
  at kOS.Execution.CPU.ExecuteInstruction (IProgramContext context) [0x00000] in <filename unknown>:0 
 
(Filename: C:/buildslave/unity/build/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

Code Fragment

File                 Line:Col IP   label opcode operand
----                 ----:--- ---- -------------------------------  
                        0:0   0000  jump 1 
interpreter history     1:1   0001 @0001 push $<argstart> 
interpreter history     1:6   0002 @0002 push $abc 
interpreter history     1:6   0003 @0003 call edit() 
interpreter history     1:6   0004 @0004 pop 
interpreter history     2:1   0005 @0005 push $<argstart> 
interpreter history     2:1   0006 @0006 push $<argstart> 
interpreter history     2:5   0007 @0007 push abc 
interpreter history     2:5   0008 @0008 push null 
interpreter history     2:5   0009 @0009 call run() 
interpreter history     2:5   0010 @0010 pop 
interpreter history     2:5   0011 @0011 pop 
interpreter history     2:1   0012 @0012 push $<argstart> 
interpreter history     2:1   0013 @0013 push $<argstart> 
interpreter history     2:5   0014 @0014 push abc 
interpreter history     2:5   0015 @0015 push null 
interpreter history     2:5   0016 @0016 call run() 
interpreter history     2:5   0017 @0017 pop 
interpreter history     2:5   0018 @0018 pop 
interpreter history     2:1   0019 @0019 push $<argstart> 
interpreter history     2:1   0020 @0020 push $<argstart> 
interpreter history     2:5   0021 @0021 push abc 
interpreter history     2:5   0022 @0022 push null 
interpreter history     2:5   0023 @0023 call run() 
interpreter history     2:5   0024 @0024 pop 
interpreter history     2:5   0025 @0025 pop 
interpreter history     3:7   0026 @0026 push False 
interpreter history     3:7   0027 @0027 not 
interpreter history     3:7   0028 @0028 br.false 11 
interpreter history     3:13  0029 @0029 pushscope 1 0 
interpreter history     4:1   0030 @0030 push $<argstart> 
interpreter history     4:1   0031 @0031 push $<argstart> 
interpreter history     4:5   0032 @0032 push abc 
interpreter history     4:5   0033 @0033 push null 
interpreter history     4:5   0034 @0034 call run() 
interpreter history     4:5   0035 @0035 pop 
interpreter history     4:5   0036 @0036 pop <<--INSTRUCTION POINTER--
interpreter history     5:1   0037 @0037 popscope 1 
interpreter history     5:1   0038 @0038 jump -12 
interpreter history     5:0   0039 @0039 nop 
                        0:0   0040  EOF 

(Filename: C:/buildslave/unity/build/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

kOS: Stack dump: stackPointer = -1
000      kOS.Safe.Execution.VariableScope
          ScopeId=1, ParentScopeId=0, ParentSkipLevels=1 IsClosure=False
```
It looks line an additional `pop` causes stack misalignment.
Not in the interpreter it works fine:
![screenshot3](https://cloud.githubusercontent.com/assets/11031560/7675035/c462e92a-fd3b-11e4-92ef-a4b88b722797.png)
```
Code Fragment
File                 Line:Col IP   label opcode operand
----                 ----:--- ---- -------------------------------  
                        0:0   0000  jump 16 
archive/caller          3:3   0001 @0001 push $program-abc* 
archive/caller          3:3   0002 @0002 push -1 
archive/caller          3:3   0003 @0003 eq 
archive/caller          3:3   0004 @0004 br.false 8 
archive/caller          3:3   0005 @0005 push $program-abc* 
archive/caller          3:3   0006 @0006 push $<argstart> 
archive/caller          3:3   0007 @0007 push abc 
archive/caller          3:3   0008 @0008 push null 
archive/caller          3:3   0009 @0009 call load() 
archive/caller          3:3   0010 @0010 pop 
archive/caller          3:3   0011 @0011 store 
archive/caller          3:3   0012 @0012 call $program-abc* 
archive/caller          3:3   0013 @0013 pop 
archive/caller          3:3   0014 @0014 push 0 
archive/caller          3:3   0015 @0015 return 0 deep 
archive/caller          3:3   0016 @0016 push $program-abc* 
archive/caller          3:3   0017 @0017 push -1 
archive/caller          3:3   0018 @0018 store 
archive/caller          1:1   0019 @0019 push $<argstart> 
archive/caller          1:7   0020 @0020 push 1 
archive/caller          1:9   0021 @0021 push 0 
archive/caller          1:8   0022 @0022 div <<--INSTRUCTION POINTER--
archive/caller          1:8   0023 @0023 call print() 
archive/caller          1:8   0024 @0024 pop 
archive/caller          2:7   0025 @0025 push False 
archive/caller          2:7   0026 @0026 not 
archive/caller          2:7   0027 @0027 br.false 8 
archive/caller          2:13  0028 @0028 pushscope 1 0 
archive/caller          3:3   0029 @0029 push $<argstart> 
archive/caller          3:3   0030 @0030 push $<argstart> 
archive/caller          3:3   0031 @0031 call 1 
archive/caller          3:3   0032 @0032 pop 
archive/caller          4:1   0033 @0033 popscope 1 
archive/caller          4:1   0034 @0034 jump -9 
archive/caller          4:0   0035 @0035 nop 
                        0:0   0036  EOP 
```

**Comment by Dunbaratu** [comment] 2015-05-18 16:23
So are you saying that to make the bug happen requires BOTH that the RUN command is inside a loop body, AND that loop body is in the interpreter?

**Comment by Dunbaratu** [comment] 2015-05-18 16:30
Looking at the output_log dump you show above, it's only showing the exception it got trying to use the KSPLogger and failing at that.  That means it was attempting to show some other exception first, and got a second exception while attempting to show the first exception.  Was there an exception a little bit above this point in the log that isn't being shown?

**Comment by abenkovskii** [comment] 2015-05-18 16:44
> So are you saying that to make the bug happen requires BOTH that the RUN command is inside a loop body, AND that loop body is in the interpreter?

Yes.

> Was there an exception a little bit above this point in the log that isn't being shown?

Ok. I'll reproduce it again and send the whole log via dropbox like I usually do.

**Comment by abenkovskii** [comment] 2015-05-18 17:40
https://www.dropbox.com/s/dj0gi4mv6uuwxgc/run_in_loop.txt?dl=0
![screenshot1](https://cloud.githubusercontent.com/assets/11031560/7686283/53b1e61a-fd9d-11e4-8d41-be3246a83828.png)
The same thing happens when you use `run` in any closures in the interpreter:
https://www.dropbox.com/s/isclgc0vdsk7s04/bug_run_closures.txt?dl=0
![screenshot5](https://cloud.githubusercontent.com/assets/11031560/7686333/c1fc13d4-fd9d-11e4-989f-ac5e8db30b48.png)

**Comment by Dunbaratu** [comment] 2015-12-29 21:09
This is so old I'm inclined to label it as `wontfix` just because it's messy to reproduce on the current code.

**Closed** 2015-12-29 21:10 UTC
Labels: wontfix
