### ISSUE TITLE
Kerbal counting bug causes vessel mass to grow

### ISSUE THREAD

**Issue by drasive** [KSP-KOS/KOS#1652] opened 2016-05-15 22:41 UTC
When kOS (v0.20.0) and Realism Overhaul (v11.0.0) are both installed and the active vessel contains a crew member (in editor or in flight), the vessel mass grows forever.
This makes manned flight impossible.

@NathanKell mentioned that this is an issue with how kOS implements GetModuleMass in [issue 1234](https://github.com/KSP-RO/RealismOverhaul/issues/1234) of Realism Overhaul.
I am happy to implement the bugfix, if someone can provide me with the available info on the cause.

Tested on KSP 1.1.2

**Comment by tomekpiotrowski** [comment] 2016-05-15 22:42
A duplicate of #1643, which was fixed. The next release, which should come out today, will contain the fix.

**Closed by tomekpiotrowski** 2016-05-15 22:42 UTC
Labels: duplicate
