### ISSUE TITLE
KOS does not respect time acceleration for RemoteTech signal delays

### ISSUE THREAD

**Issue by akors** [KSP-KOS/KOS#1167] opened 2015-09-22 11:27 UTC
Hi!

I noticed that when running commands on a probes terminal, the RemoteTech signal delay is correctly implemented and it takes the command a while to get executed.

When using non-physical timewarp, however, the time delay counter still runs in unaccelerated real time while the rest of the game runs in timewarp.

When using physical timewarp, the delay counter is accelerated as well.

**Comment by Dunbaratu** [comment] 2015-09-24 03:26
I think this is a duplicate of issue #723

**Closed by Dunbaratu** 2015-09-24 03:26 UTC
