### ISSUE TITLE
adjusting power consumption?

### ISSUE THREAD

**Issue by Schnobs** [KSP-KOS/KOS#1382] opened 2016-01-17 23:35 UTC
Can one modify the power consumption of kOS Machines? Asking for a friend...

Seriously: Realism Overhaul integrates kOS by simply adding a kOS Machine to every command module [(MM Code)](https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RealismOverhaul_Global_Config.cfg#L69). However, the power demands are rather extreme compared to other RO parts and would need to be reduced (probably to zero) in oder to make kOS usable.

Maybe I'm missing the obvious, but I cannot change the EnergyCost through ModuleManager. Can it be done, and if not, would you please be willing to make it possible?

**Comment by erendrake** [comment] 2016-01-17 23:50
Power consumption is adjustable now because it is directly related to disk size. Reduce disk size, reduce power consumption!

**Comment by Dunbaratu** [comment] 2016-01-18 04:31
I am still of the opinion that kOS power usage is still too punishing, especially for code that spends most of its time looping over a wait not doing much.  One future idea we've been knocking around is to pay for electricity in "micropayments" per instruction run - so during times when your program is merely running a few boolean tests per update and that's it (i.e. it's stuck in a WAIT and maybe has as WHEN trigger or two in the background being checked) it uses way less power than when it's actually running the CPU full bore at 100%.

**Comment by erendrake** [comment] 2016-01-18 04:37
I agree with @dunbaratu that we want to do a much better job of helping users manage their power usage in future releases.

**Comment by hvacengi** [comment] 2016-01-18 11:45
This is essentially a duplicate of #1009.  There are a couple of components that need to be adjusted: as noted above, the balance needs to be improved to account for actual cpu usage; additionally, the power usage should not be hard coded, but rather a component of the parts' configuration files. 

I did not realize that RO forced each pod to have a processor on it. You might want to make you default boot script force the cpu to shutdown (thereby disabling power consumption) so that you only need to power the one or two processors that are actually doing work.

**Comment by Schnobs** [comment] 2016-01-18 13:12
I'm afraid I did not explain properly... first off, "RO" is [Realism Overhaul](https://github.com/KSP-RO), the modpack that attempts to turn KSP into a serious simulator. Part stats have been scaled according to known data; 1EC/s has been declared to be 1kW. On that scale, a kOS Machine currently demands 200W.

To put this into perspective, the Voyager probes weighed 825kg and had 480W worth of RTGs at launch time. Power demand was on the order of 360W, with a ~400W peak at the time of flyby. It is not an accident that one can build a Voyager replica in RO that comes out pretty close to the original. Especially, it also has little headroom in terms of electrical power.

In order to integrate kOS into Realism Overhaul, it will be necessary to dramatically reduce the power demand of the processor -- probably to zero in most cases, as the command modules already draw as much power as their historical counterparts, regardless of how the player chooses to control his vessel.

That's why I'm asking if that stat could possibly be changed through ModuleManager.

**Comment by Dunbaratu** [comment] 2016-01-18 14:50
> 1EC/s has been declared to be 1kW.

That is a scale the RO people invented from thin air.  The stock game does not makes this claim.

That being said, there is no reason the constant shouldn't be part of the part.cfg file and thus alterable via modulemanager.   I'm not happy with the fact that it's not, for reasons that have nothing to do with RO.  But be aware that the very notion of it being a constant value is totally unrealistic in the first place anyway, whether it's a large or a small constant.  Real computers don't draw the same power when the cpu is 100% pegged as they do when it's mostly waiting in an idle I/O blocked state.  We want to fix that later, which means anything we do now, and anything you do on your end to work with it, is getting obsoleted later.

Eventually what had been a constant in the config file would become more of a coefficient multiplier operating on micropayments instead  (i.e. a teeny tiny cost per instruction actually executed, so a program that has a loop with just a few instructions and a wait will draw less power than one that busy loops).

**Comment by Dunbaratu** [comment] 2016-01-18 15:04
The reason I'd like to see electric charge based on some multiplier value in the part config file is that it would make it easier to set up multiple different eras of CPU at different tech levels that draw differing amounts of power.   It's got nothing to do with RO, but it would have the side effect of giving RO what is being asked for here.

Right now it's calculating it from here to begin with:
```
 protected const float BASE_POWER = 0.04f;
```
In Volume.cs, rather than from a config value.  (Never mind that it really doesn't make sense to base it on disk space in the first place.  It's just that that's the only real configurable setting we had back when that code was written.)

**Comment by Schnobs** [comment] 2016-01-19 02:06
> That is a scale the RO people invented from thin air. The stock game does not makes this claim.
Of course. But some scale had to be found for the purpose.

>  Real computers don't draw the same power when the cpu is 100% pegged as they do when it's mostly waiting in an idle I/O blocked state.

Has it always been thus? IIRC the first x86 to have that feature was the 486, and Windows didn't support it until much later (WinXP?). I know nothing about other architectures, much less about the sequencer type devices they used in the 60s.

**Comment by hvacengi** [comment] 2016-01-28 16:20
I'm going to close this duplicate issue since it looks like the discussion has died down.  Feel free to continue the conversation here though.

**Closed by hvacengi** 2016-01-28 16:20 UTC
Labels: duplicate, enhancement
