### ISSUE TITLE
issue with duplicate module field names

### ISSUE THREAD

**Issue by UglyRooster** [KSP-KOS/KOS#3075] opened 2023-01-03 03:11 UTC
Related to issue 2666.
The SSME engine has two fields named "throttle".  The first selects use of the main throttle or independent throttle.  As a result the 2nd one (the actual independent throttle) isn't accessible.

Additionally, the check in Allfields, FieldIsVisible doesn't actually return true for the 2nd throttle, even when it is visible in the gui.  Possibly the field isPersistant could also be used in the FieldisVisible check, as isPersistant seems to be only true for fields that appear in the GUI (even if at times hidden).  
My test code shows isPersistant true for the scaler throttle even when using the main throttle.  This seems fine since would be nice to set the independent throttle BEFORE enabling it!

Not sure how one access to the 2nd or more duplicated field.  Would be nice if get/setfield had an optional parameter to get at the 2nd field....

**Comment by nuggreat** [comment] 2023-01-03 03:22
Duplicate of issue #2943
Though as with modules themselves there having a method to get fields by index as apposed to just name would be nice though this is the only module this has be a problem for and only recently.

**Comment by UglyRooster** [comment] 2023-01-04 01:08
Was thinking of, in the case of duplicates, in addition to keeping the current behavior, add the duplicates with a suffix representing the type.  And if their are duplicates again, adding numbers.  

Allfields for the SSME module would return in part:
throttle
throttle_b   is a bool
throttle_s    is a single

What are the negative side effects of using isPersistant in FieldisVisible.  
Possibly during development, the fields only allowed because of isPersistant could have the prefix "p_"

**Closed** 2024-08-01 11:37 UTC
Labels: duplicate
