### ISSUE TITLE
When & On triggers get overwritten.

### ISSUE THREAD

**Issue by SlavDimov** [KSP-KOS/KOS#2312] opened 2018-07-31 07:37 UTC
I'm playing Realism Overhaul & I have test flight installed, so I am trying to write a script that will monitor my user defined engine groups and if one of the engines in the group stops or slows down it will kill all of the engines in that group.
I managed to write everything except for the part where I need the actual WHEN trigger.

Here is a snipped of my code:

`
local function SET_WATCH {
    declare local parameter ENGINES_.
    declare local parameter STAGE_. //if set to true a stage will be executed on failure.
    print ENGINES_.
    when ENGINES_THURST_IS_DIFFERENT(ENGINES_) then {
        for ENGINE in ENGINES_ {
            ENGINE:SHUTDOWN.
        }
        if STAGE_ = True {
            stage_and_ready().
        }
        //continue to monitor engines.
        return true.
    }
    
}

local function ENGINES_THURST_IS_DIFFERENT {
    declare local parameter ENGINES_.

    declare local MIN_THRUST is ENGINES_[0]:thrust.
    declare local MAX_THRUST is MIN_THRUST.

    for ENGINE in ENGINES_:sublist(1, ENGINES_:length) {
        if ENGINE:thrust > MAX_THRUST {
            SET MAX_THRUST TO ENGINE:thrust.
        } else if ENGINE:thrust < MIN_THRUST {
            SET MIN_THRUST TO ENGINE:thrust.
        }
    }
    
    //wait until thrust parameter refreshes
    //and/or engine has been started,
    //otherwise it will get a NaN value
    if MAX_THRUST > 0 {
        declare local DIFF is (100 - IN_PERCENT(MIN_THRUST, MAX_THRUST)).
        //DEBUG
        // print "diff: " + DIFF.        
        //if the difference in thrust is bigger than the max allowed
        if DIFF > MAX_DIFF {
            return true.
        }
    }
    return false.
}

`

Using the print statement in SET_WATCH I can see that I pass different engine groups each time the SET_WATCH is called.

**Expected behavior:**
SET_WATCH should set up a new when trigger each time it is called. Which should allow me to monitor 
all of the different engine groups at the same time and kill every one of the groups independently if a failure occurs.

**Actual behavior:**
SET_WATCH overwrites each when trigger with the next. This way only the last group of engines is being monitored.

**Tests:**
Input:
ENGINE_GROUP_1
ENGINE_GROUP_2

Output:
only ENGINE_GROUP_2 is monitored and shutdown on failure.
--------------------------------------------------------------------
Input:
ENGINE_GROUP_2
ENGINE_GROUP_1

Output:
only ENGINE_GROUP_1 is monitored and shutdown on failure.

How are the triggers being implemented in KOS code? Are they on a separate thread? I believe they are , because if I write a "wait" in the trigger the whole scripts continues and only the trigger waits. (Correct me if I'm wrong)

How can I work around that? I want KOS to create a new trigger for each group of engines.
Obviously I cant just write them one by one, because:
1. I have arbitrary number of engine groups in different vessels.
2. I don't think it will change anything. I suspect this behavior is, because the When trigger evaluates the return statement of the ENGINES_THURST_IS_DIFFERENT function, which is only true or false so I guess it somehow decides I am talking about the same thing and overwirtes the previous trigger?

I also tried with an ON trigger, but nothing changed....

I'm on KOS's latest version using CKAN  with KSP 1.2.2.
Thank you for your help.

**Comment by SlavDimov** [comment] 2018-07-31 14:36
Yes, I believe we encounter the same problem.

I call this function every time I need to set a trigger:
`
local function STAGE_ENGINES {
    declare local parameter ENGINE_GROUP_LIST, ENGINE_WITH_STAGE_RGX.

    if MATCH_ENGINES_TAG(ENGINE_GROUP_LIST, ENGINE_WITH_STAGE_RGX) {
        //DEBUG
        //print "STAGE: " + ENGINE_GROUP_LIST.
        SET_WATCH(ENGINE_GROUP_LIST, True).
    } else {
        //DEBUG
        //print "NORMAL: " + ENGINE_GROUP_LIST.
        SET_WATCH(ENGINE_GROUP_LIST, False).
    }
}
`

Now the question is: How can I force kOS to distinguish between the different trigger creations?
I obviously can't make the Equals() check faster, because I have to check all the engines in order to see if any of them is performing differently than the others.

**Comment by Dunbaratu** [comment] 2018-08-01 17:02
Duplicate of #2272

**Closed** 2018-08-01 17:03 UTC
Labels: duplicate
