### ISSUE TITLE
OPENPATH(PATH) doesn't RETURN a Boolean if the file does not exist.

### ISSUE THREAD

**Issue by stevemeacham** [KSP-KOS/KOS#2774] opened 2020-10-20 20:25 UTC
kOS DOC states that OPEN(PATH) will return a Boolean if the specified path does not exist. It does not. Rather, it throws an error and terminates the program, dropping to the terminal.

The workaround is to call EXISTS(PATH) first and only OPEN(PATH) if TRUE.

If this is a DOC issue, I'll gladly submit a pull request.  If it's a code issue, I'll defer to others or wait until I become familiar with the codebase.

**Comment by Dunbaratu** [comment] 2020-10-20 20:57
I took a peek at the code and it should be possible to fix this to match what the docs say with just a few lines.  Thanks for reporting it.

**Comment by nuggreat** [comment] 2020-10-20 22:04
this looks related to or a duplicate of issue #2430

**Comment by stevemeacham** [comment] 2020-10-20 22:11
I agree that this is a shorter version of issue #2430.  I missed it when I searched for a matching issues before posting.  I'll let you decide whether or not to close one or the other.

**Closed** 2020-10-26 16:00 UTC
