### ISSUE TITLE
Implement this to remove ADDON BINDING message about kOS.Safe

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#3001] opened 2021-08-17 23:04 UTC
The log shows a message about ADDON BINDING for kOS.Safe failing, whatever that means:

`
ADDON BINDER: Cannot resolve assembly: kOS.Safe, Culture=neutral, PublicKeyToken=null
`

Linuxgurugamer noted this problem in other mods and how to fix it - here's an example of it:

https://github.com/jrbudda/KerbalEngineer/issues/52

I don't know if this message matters - it's been there for ages - but anything that removes a spurious message is good.  To work it needs to show that either kOS.Safe depends on kOS, or that it is its own separate assembly by having its own  KSPAssembly directive just like kOS.dll has in its AssemblyInfo.cs file.

**Comment by JonnyOThan** [comment] 2024-08-01 11:41
dupe of #3049

**Closed by JonnyOThan** 2024-08-01 11:41 UTC
Labels: duplicate
