### ISSUE TITLE
[bug] can't unset boot file in the VAB

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#761] opened 2015-04-08 21:05 UTC
This issue was split from #758.

**Comment by ZiwKerman** [comment] 2015-04-08 21:07
It is in the docs.

Usually you should keep the default boot.ks as neutral as possible as a workaround

I have mine consisting of 1 line
```
   switch to 1.
```

**Comment by abenkovskii** [comment] 2015-04-08 21:09
@ZiwKerman, but @erendrake says it is a bug.

**Comment by ZiwKerman** [comment] 2015-04-08 21:10
It's not a bug if it's documented. This is a limitation of the UI tweakable and of how the boot files were programmed

There is a workaround possible, but we had other mattters to attend to.

**Comment by erendrake** [comment] 2015-04-08 21:19
@ZiwKerman It is documented, but it really sucks, even if we have to add a "clear boot selection" button i think its better than locking someone into a boot file. its not that i think this is a super high priority issue I just want to have it recorded that we should do something if we have time.

**Comment by ZiwKerman** [comment] 2015-04-08 21:20
@erendrake: I agree that we need to add the ability to set boot script to "None".

**Comment by erendrake** [comment] 2015-04-08 21:26
could we simply add another option in the slider with some kind of special sentinel "none" value that the processor knows means "i dont want a boot file"?

**Comment by ZiwKerman** [comment] 2015-04-08 21:27
That is what I intend to do

**Comment by hvacengi** [comment] 2015-04-09 03:49
As it is, doesn't the first boot file (usually boot.ks) get listed twice?  Or is that the last boot file?  I seem to recall seeing that when I was looking into how to revise the boot file logic (which I never did, and I'm happy @ZiwKerman is handling that).  If one file gets listed twice, one of the instances could be used as a "none" option.

**Comment by ZiwKerman** [comment] 2015-04-14 15:38
Solved and merged. @erendrake  you can close this one.

**Closed** 2015-04-14 15:38 UTC
Labels: bug
