### ISSUE TITLE
"Some or all kOS textures were not found"

### ISSUE THREAD

**Issue by BlueTiger12** [KSP-KOS/KOS#1484] opened 2016-02-29 23:22 UTC
Hi

I get the Error Message "Some or all kOS textures were not found" even i have the correct data structure. KOS itself was still working.
I was able to hunt the error down.
Problem was that i had a KSP install of 1.0.4 and one of 1.0.5.
I deleted the version 1.0.4 and changed the shortcut to it, so that the "target" was the KSP install 1.0.5..
But i forgot to change the "Start in" line so it was still pointing at the deleted directory.
After changing this to the correct directory it worked again.

I am not sure if that is a bug or intended behaviour, so i am opening an issue for it nevertheless.
![kos_error](https://cloud.githubusercontent.com/assets/12852382/13412367/13f9a3ea-df43-11e5-81c5-d695174fc883.png)

**Comment by Dunbaratu** [comment] 2016-02-29 23:24
What does this have to do with kOS?  It sounds like it's just a matter of how you set up KSP itself to use the executable from one install but the data files from a different install.

**Comment by hvacengi** [comment] 2016-02-29 23:30
The "Start in" folder being selected incorrectly would probably break other mods as well.  Star in" essentially tells the program to act as if it was run from the specified folder.  As a result, any "relative" path will not correctly load.  You would probably also find that the KSP.log file is not updated inside of the 1.0.5 folder, because it's trying to be written inside of the 1.0.4 folder (though I could be wrong about that).

This isn't so much of an "intended behavior" so much as a result of an error that causes unpredictable performance.  I'm going to go ahead and close the issue since you already figured out how to fix it.

**Closed by hvacengi** 2016-02-29 23:30 UTC

**Comment by BlueTiger12** [comment] 2016-02-29 23:31
The thing i was wondering is, that everything else worked just fine. All other PNGs and Icons were loaded. So i thought it might be a wronk internal reference.

You are right, just found in on my Desktop.

Ok thanks for clearing it up for me:-)
Thanks for your great mod:-)
