### ISSUE TITLE
array index is out of range on WARP

### ISSUE THREAD

**Issue by Tabris83** [KSP-KOS/KOS#674] opened 2015-03-16 11:54 UTC
i've been getting this error seemingly randomly for the past day.
this is the [code](https://github.com/Tabris83/kOS-Archive/blob/master/launch.ks)
here is the log extract
````
kOS: At launch.ks on 1, line 99
	PRINT "Current ALT: " +round(SHIP:ALTITUDE/1000) +"Km " AT (0,5).
                                                               ^
Called from boot.ks on 1, line 13
RUN launch.
^
Called from boot on 1, line 1
CLEARSCREEN.
^

 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

System.IndexOutOfRangeException: Array index is out of range.

  at TimeWarp.setRate (Int32 rateIdx, Boolean instantChange) [0x00000] in <filename unknown>:0 

  at TimeWarp.SetRate (Int32 rate_index, Boolean instant) [0x00000] in <filename unknown>:0 

  at kOS.Binding.BindingTimeWarp.<AddTo>b__9 (System.Object val) [0x00000] in <filename unknown>:0 

  at kOS.Safe.Binding.BoundVariable.SaveValue () [0x00000] in <filename unknown>:0 

  at kOS.Binding.BindingManager.PostUpdate () [0x00000] in <filename unknown>:0 

  at kOS.Execution.CPU.PostUpdateBindings () [0x00000] in <filename unknown>:0 

  at kOS.Execution.CPU.Update (Double deltaTime) [0x00000] in <filename unknown>:0 
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

Code Fragment

File                 Line:Col IP   opcode operand

----                 ----:--- ---- --------------------- 

1/launch.ks            98:91  0750 push Km  

1/launch.ks            98:90  0751 add 

1/launch.ks            98:101 0752 push 0 

1/launch.ks            98:103 0753 push 4 

1/launch.ks            98:103 0754 call printat() 

1/launch.ks            99:8   0755 push Current ALT:  

1/launch.ks            99:31  0756 push $ship 

1/launch.ks            99:36  0757 push altitude 

1/launch.ks            99:36  0758 getmember 

1/launch.ks            99:45  0759 push 1000 

1/launch.ks            99:44  0760 div 

1/launch.ks            99:44  0761 call roundnearest() 

1/launch.ks            99:24  0762 add 

1/launch.ks            99:52  0763 push Km  

1/launch.ks            99:51  0764 add 

1/launch.ks            99:62  0765 push 0 

1/launch.ks            99:64  0766 push 5 <<--INSTRUCTION POINTER--

1/launch.ks            99:64  0767 call printat() 

1/launch.ks           102:2   0768 push $throttle* 

1/launch.ks           102:2   0769 push 108 

1/launch.ks           102:2   0770 store 

1/launch.ks           102:2   0771 push 118 

1/launch.ks           102:2   0772 addtrigger false 

1/launch.ks           102:2   0773 push throttle 

1/launch.ks           102:2   0774 push True 

1/launch.ks           102:2   0775 call toggleflybywire() 

1/launch.ks           103:2   0776 push $warp* 

1/launch.ks           103:2   0777 push 112 

1/launch.ks           103:2   0778 store 

1/launch.ks           104:2   0779 push $steering* 

1/launch.ks           104:2   0780 push 80 

1/launch.ks           104:2   0781 store 

1/launch.ks           104:2   0782 push 114 


 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

kOS: Stack dump:

005      SubroutineContext: {CameFromInstPtr 16}

004      SubroutineContext: {CameFromInstPtr 11}

003      SubroutineContext: {CameFromInstPtr 69}

002      SubroutineContext: {CameFromInstPtr 27}

001 SP-> 0

000      Current ALT: 70Km 


 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

kOS: Popping context 2
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

kOS: FlightControlManager: ToggleFlyByWire: throttle False
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

kOS: FlightCtrlParam: Enabled: throttle True
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

kOS: FlightControlManager: ToggleFlyByWire: steering False
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

kOS: FlightCtrlParam: Enabled: steering True
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

kOS: Removed Context File                 Line:Col IP   opcode operand
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

kOS: Deleting 0 pointers and restoring 0 pointers
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

kOS: New current context File                 Line:Col IP   opcode operand
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

in CPUListChanged(): itChanged = False, newList.Count=1, availableCPUs.Count=1

Reference Frame: Inertial
````

[full log, code, screenshot](https://www.dropbox.com/sh/sqffnebd414dpxd/AAC-pO8krR-7IaCZLb7yRphwa?dl=0)
output_log(2).txt is the newer log and has 3 more occurrences, each with a different line quoted.

**Comment by Dunbaratu** [comment] 2015-03-18 06:21
The bug is getting misreported as to what line is at fault.  I *think* it's because the timewarp was set to level 5 at a time when you can't have 5 levels of time warp (are you in atmosphere?).

The exception happens because of a bogus value being sent to KSP's time warp API.  KSP doesn't protect itself very well against bogus input and often throws system exceptions when the value isn't right.  In this case it allowed itself to look past the end of an array when being given an array index that was too large.

So there are two different bugs here, as I see it:
  1. The error is getting reported at totally the wrong place in the code.  Dunno why.
  2. We should protect SET WARP a bit better and detect when the value isn't going to work and throw our *own* exception.

**Comment by TDW89** [comment] 2015-03-18 21:49
I have been experiancing something simmilar.

My script crashes trying to get the terrainheight of a geoposition. It has sucsessfuly done this for a large number of other geopositions but fails up near the north pole (after running for 6-8h with the IPU set to 2000).
After the script crashed I tryed manualy inputing `print p2:terrainheight.` and got the same error message. However, `print p2:lat. print p2:lng.` both work and `print latlng(p2:lat,p2:lng):terrainheight.` also worked.
![img](http://drive.google.com/uc?export=view&id=0B2X2pcwft9VdcGZya2NrZ1Z1RDQ)

script is [here](https://github.com/TDW89/kOS-Pathfinder/archive/v0.1.zip) if you want to reproduce it. Let me know if you want logs and i will run the script again.

**Comment by Dunbaratu** [comment] 2015-03-18 21:50
The log file is more useful.  It tells us exactly which routine the crash occurred in.

**Comment by TDW89** [comment] 2015-03-18 21:51
Will get the log to you tomorrow evening.

**Comment by TDW89** [comment] 2015-03-19 06:59
[ksp.log](https://drive.google.com/file/d/0B2X2pcwft9VddUMzVXNMU1dPazQ/view?usp=sharing)
[player.log](https://drive.google.com/file/d/0B2X2pcwft9VdMmxUQzBIMWdLYVE/view?usp=sharing)

**Comment by Dunbaratu** [comment] 2015-03-19 07:15
Okay the problem is in our C# code here in GeoCoordinates.GetTerrainAltitude():
```
                bodyUpVector = QuaternionD.AngleAxis(Lat, Vector3d.forward/*around Z axis*/) * bodyUpVector;
                bodyUpVector = QuaternionD.AngleAxis(Lng, Vector3d.down/*around -Y axis*/) * bodyUpVector;

                alt = bodyPQS.GetSurfaceHeight( bodyUpVector ) - bodyPQS.radius ;
```
The problem is that bodyPQS.GetSurfaceHeight does not like the bodyUpVector it's being passed, and the KSP API instead of detecting that and throwing its own exception, ends up just trying to use it as-is and dying.

I think it's a gimbal lock problem.  The Y axis is parallel to the axis of the North Pole of the current sphere of influence body.  So when we try to rotate a vector around the Y axis, when the vector is already pointing straight up the Y axis (as it is at latitude 90, the north pole), apparently the Unity API calls for Quaternion are returning something bogus instead of returning the vector unchanged.

I'd argue that the correct behavior in a condition of gimbal lock like that *should* be to just return the vector unchanged.  "Rotate this vector around the axis of ... itself"... "Uhm, okay, if that's what you want, I'll ignore you and just give the same vector back to you."...

But apparently that's not what it's doing.  It seems to be returning something bogus back.

I guess it can probably be fixed by us adding a protection to see if the latitude is 90 or -90 and making a special case for that.  But until then, you can try to fix it in your own code by protecting against that condition.

**Comment by TDW89** [comment] 2015-03-19 07:42
Thanks for the fast reply.

The issue seemed to disappear when i rounded a lot of the numbers used in the script (5dp) including the lat &lng. Felt the length of the numbers returned by the script was uunnecessary, especially when they were a bit floaty anyway.

**Comment by erendrake** [comment] 2015-04-03 01:59
We need to clamp this value to something valid. We can silently select the closest possible.

**Comment by hvacengi** [comment] 2015-04-03 17:48
With relation to the original issue reported by @Tabris83 (the array exception in executing a time warp): I have occasionally run into this issue at the fringe of the atmosphere.  I wasn't able to determine if it was just reading acceleration from the vessel rotating, or if it was delayed in clearing the "physical warp" status of the craft.  I worked around it in the script by reading the warpmode variable and clamping my warp level there.
```
set maxwarp to 7.
if (warpmode = "physics") { set maxwarp to 3. }
set warp to min(tgtwarp, maxwarp).
```
It would certainly be possible to do the same logic within the internal KOS logic as well.  I'll see if I have any time this weekend to look into it.

Unfortunately, that doesn't necessarily line up with the user expectation.  Is it better to error out when setting a higher warp that is available, or to go to the highest possible warp?  In my opinion setting the highest warp possible **and** display a similar message to what stock KSP shows when you attempt to set the warp mode to a level higher than currently allowed.

Any one else have an opinion on the best way to handle this?

**Closed** 2015-04-14 01:21 UTC
Labels: bug
