### ISSUE TITLE
bootfilename can't be set to a path or file not on root directory of core

### ISSUE THREAD

**Issue by nuggreat** [KSP-KOS/KOS#2199] opened 2017-12-22 10:06 UTC
kOS doesn't let you change the bootfilename to a path or even the string for a path it only seems to accept the string of a file name and will only run the file if it is found on the root volume of the core.

If a file is not in the root directory i couldn't find a way to set the bootfilename to that location and have the targeted file run

File called "my_example1.ks" found at path: "1:/other_boot_files/my_example1.ks"
```
SET CORE:BOOTFILENAME TO PATH("1:/other_boot_files/my_example.ks").  //will crash
SET CORE:BOOTFILENAME TO "1:/other_boot_files/my_example.ks".  //will not run my_example.ks when rebooted
```
But if the file is found at 1:/ then you can set BOOTFILENAME to that file so long as you only use the name of the file
File called "my_example2.ks" found at path: "1:/my_example2.ks"
```
SET CORE:BOOTFILENAME TO "1:/my_example2.ks".//will not run my_example2 when rebooted
SET CORE:BOOTFILENAME TO "my_example2.ks".//will run my_example2 when reboot
```

This seems at odds with the rest of the way we are suppose to handle files now.  if it needs to be kept that way for backwards compatibility then it would be nice to have another version of bootfilename that could be set to paths or strings that describe paths

**Comment by Dunbaratu** [comment] 2017-12-22 11:45
This is a duplicate of issue #2165  .

**Closed** 2017-12-22 11:45 UTC
Labels: duplicate
