### ISSUE TITLE
Add beep sound to in-game terminal. 

### ISSUE THREAD

**Issue by akrasuski1** [KSP-KOS/KOS#1036] opened 2015-05-20 21:47 UTC
EDIT: Changed description.

It is already possible to do beep via telnet interface, but the in-game tutorial should also respond to ASCII 7th character (BEL).

**Comment by hvacengi** [comment] 2015-05-21 00:14
I may be missing the difference, but is this a duplicate of #979 ?

**Comment by Dunbaratu** [comment] 2015-05-21 01:47
It's a duplicate because of how it got described here.

What I actually wanted as an issue was "implement the interpretation of the BEL char in the GUI terminal so it act just like telnet when someone uses the KSlib beep char."

**Comment by Dunbaratu** [comment] 2015-05-21 16:40
Darn it, I really hate it when something supposedly simple ends up being a major pain because of how the infrastructure is laid out.

I ran into this problem:

When you ``PRINT blarg.``, for any blarg, the path the code takes to make this work is as follows:

Get the current ScreenBuffer.  Tell the ScreenBuffer to Print the string Blarg. 
When the ScreenBuffer prints the string Blarg, it stores the resulting chars in the buffer array.

Multiple times a second, the GUI terminal wakes up and checks its screenbuffer to display what it sees there.

Therefore the system doesn't support "printing" characters that don't take up an actual cell on the terminal grid.  The Terminal has a reference to the ScreenBuffer, but the ScreenBuffer doesn't have a reference to the Terminal in it, so ScreenBuffer.Print() can't just tell the terminal to beep when it sees a 0x07 char.

I think the ScreenBuffer needs a "beep is pending" flag. When it is on, the next update will issue a beep and clear the flag.  Therefore when you ScreenBuffer.Type() a beep, the next update will issue the beep from somewhere (it doesn't matter where) on the screen as it prints the characters.

**Comment by evg-zhabotinsky** [comment] 2015-05-21 20:32
Extra suggestion: add "Visual bell".
It will blink terminal until you focus it.
It will be possible to disable it through config.

"Audible bell" config option is not going to be useful I think - you can just mute whole KSP instead.

**Comment by Dunbaratu** [comment] 2015-05-21 20:48
Visual bell is a good idea.  But it should toggle per-terminal, I think, not in the config file for all of kOS.
Maybe we make a config setting for all of kOS for how it defaults when you open a new terminal, but each terminal should be able to set it independently, I think.

**Comment by erendrake** [comment] 2015-05-21 20:50
@Dunbaratu we dont currently have a way for you to address each of the connected terminals do we?

i guess what i mean is can we answer the question "how many terminals do i have open?" from kerboscript?

**Comment by Dunbaratu** [comment] 2015-05-21 20:51
hmm......
each kOS PartModule has one terminal associated.  maybe if there's a way to walk all the kOS Partmodules?  But otherwise, not we'd have to use ugly slow Reflection to get all instances of the class.

**Comment by Dunbaratu** [comment] 2015-05-21 20:52
For within the remit of this issue, I'm going to make visual bell a per-terminal setting with a button you click on in the terminal frame.  For a separate issue we can maybe talk about giving the setting some persistence and also having a default in CONFIG it draws from.

**Comment by evg-zhabotinsky** [comment] 2015-05-21 20:54
Well, what for would you need to enumerate terminals?
Can't it work the same way as changing terminal size?

**Comment by Dunbaratu** [comment] 2015-05-21 20:57
@evg-zhabotinsky  The question wasn't "can we make a list of the terminals", but "do we" already have such a list.
It was describing the current state of things - saying we don't already have such a list.  It would be easy to make one - just have the constructor update a static list every time it gets invoked, and remove it self from the list every time it gets destructed.

**Comment by Dunbaratu** [comment] 2015-05-21 20:58
@erendrake -what was the reason for wanting such a list?

**Comment by erendrake** [comment] 2015-05-21 21:00
@Dunbaratu i may have misunderstood what you meant. i thought you were saying you would want to control the 'visual bell' per terminal in script. not enabling the bell on the terminal.

**Closed** 2015-05-23 17:32 UTC
