### ISSUE TITLE
Add SCANSat integration

### ISSUE THREAD

**Issue by mferrie** [KSP-KOS/KOS#1803] opened 2016-09-04 23:41 UTC
I think it would not only add realism, but also make navigation SO much easier if kOS could access, say, biome and elevation maps from SCANSat instead of trying to create maps from LATLNG()s like I've done. The latter is possible for really small maps, but kOS rapidly hits a memory wall when I try to make a usefully large map...

**Comment by mferrie** [comment] 2016-09-04 23:41
The main purpose of this would be to make navigating rovers intelligently possible.

**Comment by hvacengi** [comment] 2016-09-04 23:49
This is a duplicate of a long standing request (issue #881) and I want to get the integration figured out. I ran into a wall when looking at the api for integration, and then other features got moved up the depth chart. I believe some one had an add on to do this using our new 3rd party add on api, I'll look for it later tonight.

**Comment by hvacengi** [comment] 2016-09-05 15:59
Found it: https://github.com/GER-Space/Kos-Scansat/releases (mod provided by @GER-Space).

I'm going to close this specific issue because it's a duplicate.

**Closed by hvacengi** 2016-09-05 15:59 UTC
Labels: duplicate
