### ISSUE TITLE
Terminal window does not hide with rest of UI

### ISSUE THREAD

**Issue by Corax** [KSP-KOS/KOS#1058] opened 2015-06-06 01:32 UTC
When the user interface is hidden (F2 key by default), any open terminal windows are still visible.

I haven't seen this reported as a bug nor documented as a feature anywhere, although it seems somewhat obvious... so I have to assume that is by design, in which case I would request the addition of a configurable setting to allow hiding the terminal along with the rest of the UI.

**Comment by Dunbaratu** [comment] 2015-06-06 01:42
Your guess that it's by design is incorrect.  The reason it's not doing it is that the claim "it seems somewhat obvious" is false.  I was unaware of the use of the F2 key, or that such a feature even existed, until your bug report.  You can go a long way, playing the game a long time, without noticing some of the lesser-used UI features.

**Comment by Corax** [comment] 2015-06-06 01:48
"Today I learned... " for both of us then ;)

**Comment by Dunbaratu** [comment] 2015-06-06 01:51
I'm trying to find somewhere in the API where I can read the state of the "UI is hidden right now" flag, and can't seem to find it with a quick search.  I presume such a flag exists somewhere.  Once it's found, it is in fact very trivial to make the GUI terminals obey them.  They're already set up to have a show/no-show flag that triggers based on other reasons, so it's not hard.  I just never heard of the feature before and have to find it in the undocumented KSP API.

**Comment by hvacengi** [comment] 2015-06-06 01:55
@Dunbaratu take a look at the code in KER.  I am pretty sure it obeys the UI setting.  And I think Nav HUD has it as a select-able option.  Which brings up that I'd prefer it to be user configurable, because I like hiding the rest of the UI and only having the terminal still visible.  (I knew about this feature, but it never occurred to me it was a bug since I saw it as useful).

**Comment by Corax** [comment] 2015-06-06 01:56
Does this look like it registers some callback?
GameEvents.onShowUI.Add(ShowUI);
GameEvents.onShowUI.Remove(ShowUI);
and
GameEvents.onHideUI.Add(HideUI);
GameEvents.onHideUI.Remove(HideUI);

**Comment by Dunbaratu** [comment] 2015-06-06 02:07
@corax - yup that looks like it.  I was looking for a flag I could read for the current state, not a callback event, which is why I didn't find it.

**Comment by Corax** [comment] 2015-06-06 10:43
On a /somewhat/ related note, would it be possible to hide or remove the terminal size information? It is not something that I'd expect to change a lot, and it is queryable from within kOS, so is there really a reason to keep it visible all the time? I find it kind of hurts suspension of disbelief.

**Comment by Dunbaratu** [comment] 2015-08-26 16:36
Given the Unity5 stuff that's going to hit us soon and how it affects everything that deals with user windows, I'm postponing working on this until we start work on the KSP 1.1 compatibility release.

(I'm going through the list of every open issue since prev release (Jun 27) and picking out which ones I can work on quickly, now that I'm getting back into coding kOS again.)

**Comment by jberkman** [comment] 2016-04-25 02:33
this WFM in 0.20; maybe was fixed in 0.19.x?

**Comment by hvacengi** [comment] 2016-05-10 16:12
Fixed via #1506

**Closed by hvacengi** 2016-05-10 16:12 UTC
Labels: enhancement
