### ISSUE TITLE
Nested function scope not defaulting to local scope

### ISSUE THREAD

**Issue by dewiniaid** [KSP-KOS/KOS#2204] opened 2017-12-26 21:43 UTC
This is a bit of an unusual bug report, since I'm not the person experiencing the bug... but the bug came about from someone using code I wrote.

[Reddit post discussing the issue](https://www.reddit.com/r/Kos/comments/7m4tkx/kos_v1140_breaking_my_code/)

From their OP:

*I use dewiniaid's library for its curve functions in a few places in my own libraries but now they are broken. Here is a sample:*

```
FUNCTION curve_normalized {
   PARAMETER fn.
   // Normalized case of a curve function.
   LOCAL minval IS fn(0).
   LOCAL maxval IS fn(1).
   LOCAL dist IS maxval - minval.
   IF dist=0 { SET dist TO 1. } // Avoid div0.
   IF minval=0 AND maxval=1 { RETURN fn@. }  // Already normalized.
   FUNCTION fnwrap {
            PARAMETER x.
            RETURN (fn(x)-minval) / dist.
   }
   RETURN fnwrap@.
}
```
*The error that occurs is undefined variable name fn at "RETURN (fn(x)-minval) / dist." which is in the fnwrap function. I suspect it to be the fact that parameters are now local in scope but I have no idea how to fix it*

---

As the author of `curve_normalized`: the intended purpose of the function is to take a function that takes inputs of (0...1) with an initially unknown range of outputs and return a wrapper that condenses the output range to the same (0...1) scale.

**Comment by hvacengi** [comment] 2017-12-26 22:03
I'm not at home so I cannot try it right now, but has the user (or have you) tried declaring fnwrap as a local function, or as an anonymous function?
```
local fnwrap is {
  parameter x.
  return (fn(x)-minval)/dist.
}
return fnwrap.
```
I didn't think we changed any of the scope closure inheritance for functions, only for script files.  But this part could have been broken at the time too.  I suspect the issue is because regardless of the `lazyglobal` setting, functions default to global declaration.  So by declaring them locally you may force the closure to inherit from the parent variable scope.  I'd have to look up how we inherit scopes to confirm, but that logically makes sense: Global functions have a parent scope of "global" not the "local" scope in which they are defined.

Again, I could be wrong though.

**Comment by romanran** [comment] 2017-12-26 22:16
Nope, adding LOCAL inside compiles and works fine!

**Comment by hvacengi** [comment] 2017-12-26 22:19
I'm going to note this as a documentation thing and ping @Dunbaratu because I suspect he can come up with a better way to describe the circumstance than my attempt above.  We need to make sure the documentation is clear regarding function scopes.

**Comment by dewiniaid** [comment] 2017-12-26 22:22
It may be breaking backwards compatibility (then again, so is this), but it might make sense to make *nested* functions default to local in scope -- I imagine that's the desired behavior most of the time.

**Comment by Dunbaratu** [comment] 2017-12-27 21:08
Having nested functions be local by default when you say nothing is not breaking backward compatibility- that's the *intent* and it's how it used to work.  Something is wrong with the latest kOS release.  I will have to look at this when I am back to kOS.

**Comment by hvacengi** [comment] 2017-12-28 17:18
I've revised the name and label again to reflect that this is a bug in the scope implementation rather than a documentation issue.

@Dunbaratu the PR you mentioned is: https://github.com/KSP-KOS/KOS/pull/2157

**Comment by Dunbaratu** [comment] 2017-12-28 19:47
@dewiniaid - I'm having a hard time reproducing the problem here with the posted bit of code at the top of this issue.  There's got to be more to it than that.

I saved your example and called it filename "fn_test.ks".
Then I wrote this and called it "fn_test_run.ks":
```
run once "fn_test". // This is the posted code at the top of this issue - the curve_normalized function

function user_sin_func {
  parameter angle.
  return sin(angle).
}

// Testing both a delegate of a built-in and a delegate
// of a user function:

set norm_builtin_sin to curve_normalized(sin@).
set norm_user_sin to curve_normalized(user_sin_func@).

print "norm_builtin_sin(0.5) = " + norm_builtin_sin(0.5).
print "norm_user_sin(0.5) = " + norm_user_sin(0.5).
```

I run this and it returns without complaint and runs the code without complaint.

It must take a more specific set of circumstances to trigger the bug.

**Comment by romanran** [comment] 2017-12-28 20:01
I confirm. Probably he has the "fnwrap" function declared in some other place as well and there is a collision.

**Comment by Dunbaratu** [comment] 2017-12-28 20:05
It could still definitely be a bug, but the description here doesn't show how to make it happen and until I can get it to happen I can't work on fixing it.

**Comment by romanran** [comment] 2017-12-28 20:08
Try adding a second function and add another "fnwrap" function inside.  I had this issue with these two modules for example:
https://github.com/romanran/ksp/blob/master/lib/Checkboxes.ks
https://github.com/romanran/ksp/blob/master/lib/Displayer.ks

Adding LOCAL before the _print functions repairs it.

**Comment by Dunbaratu** [comment] 2017-12-28 21:09
Okay I did manage to make a problem happen by inserting another function before the intended one, like so:

```
FUNCTION clasher {
  FUNCTION fnwrap {
     print "This function should never get called - it's here to cause name clash".
  }
}

FUNCTION curve_normalized {
   PARAMETER fn.
   // Normalized case of a curve function.
   LOCAL minval IS fn(0).
   LOCAL maxval IS fn(1).
   LOCAL dist IS maxval - minval.
   IF dist=0 { SET dist TO 1. } // Avoid div0.
   IF minval=0 AND maxval=1 { RETURN fn@. }  // Already normalized.
   FUNCTION fnwrap {
            PARAMETER x.
            RETURN (fn(x)-minval) / dist.
   }
   RETURN fnwrap@.
}
```

The problem was NOT that it said it doesn't exist, but that it tried calling the wrong ``fnwrap``.
with this change, when ``curve_normalized`` executes ``RETURN fnwrap@.``, the Delegate it returns is a Delegate of the *other* fnwrap, the wrong one, and then we get the complaint that the number of args mismatch (Because the other fnwrap takes zero args, and the right one takes 1 arg).

**Comment by Dunbaratu** [comment] 2017-12-28 21:48
Okay I found what broke this in PR #2154, I'm pretty sure of it.

This may require a hotfix release, because it's pretty bad.  (All my fault).

It's this diff near lines 2170 that did it:
```
-            // locks are default global while everything else is 
-            // default local:
-            StorageModifier modifier =
-                (lastSubNode.Token.Type == TokenType.declare_lock_clause ? StorageModifier.GLOBAL : StorageModifier.LOCAL);
+            // locks are default global, and functions declared at file
+            // scope are default global, while everything else is default local:
+            StorageModifier modifier = StorageModifier.LOCAL;
+            if (lastSubNode.Token.Type == TokenType.declare_lock_clause ||
+                lastSubNode.Token.Type == TokenType.declare_function_clause)
+            {
+                modifier = StorageModifier.GLOBAL;
+            }
```
Old logic before PR was:
- Always assume all functions are local when no scoping keyword given.  At outermost scope level it will end up being global anyway because there's no file scope, so this is fine.

New Logic after PR was:
- Always assume all functions are global when no scoping keyword given.

Neither one is correct now that there is file scope.

The correct approach is:
- IFF this function is at file scope, then assume it's global, else assume it's local.

I'll get started on this in a little bit.  Also, clearly some of my test examples need to be reworked to deliberately cause function name clashes that are only resolved by scoping.  (i.e. a test that will definitely trigger this bug if it exists, since it looks like I missed this case).

**Comment by dewiniaid** [comment] 2017-12-28 23:34
The original library I wrote had several curve_xx functions, each returning
a different fnwrap.  That would explain the clashing.

**Closed** 2017-12-30 07:20 UTC
Labels: bug
