### ISSUE TITLE
make new waypoints

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2614] opened 2019-09-10 05:39 UTC
Add an ability to create new waypoints rather than just being able to retrieve existing ones.

**Comment by lucaelin** [comment] 2019-09-10 11:41
duplicate of #2306 ?

**Comment by Dunbaratu** [comment] 2019-09-11 17:34
I searched for issues saying "waypoint" before making this, and for some reason that one never showed up.

**Closed** 2019-09-11 17:34 UTC
Labels: duplicate, enhancement
