### ISSUE TITLE
del and backspace in console not displaying correctly

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#730] opened 2015-04-04 13:40 UTC
sometimes console gets in a weird state where deleting a character does not update the displayed text (though cursore moves). It looks like it actually edits the text: when I press any character it updates as if delete worked normally.
P.S.
I'm yet to find a reliable way to reproduce this bug, but it looks like it happens sometimes after I `edit` something.

**Comment by abenkovskii** [comment] 2015-04-04 16:21
Now I actually found a way to reproduce it:
1. launch craft.
2. open terminal.
3. run this:
```
set i to 0.
until i > 64 {
  print i.
  set i to i + 1.
}
```
4. try running this (will throw exception): `print xxx.` 
5. now type something and press backspace
6. or press up
7. cursore moves, but text not rerenders.

**Comment by Dunbaratu** [comment] 2015-12-30 04:34
I think this might be the the problem mentioned in issue #1289, which has just been fixed in a PR.  I can't reproduce this anymore with the current develop version.

**Comment by Dunbaratu** [comment] 2015-12-30 04:37
Oh it's already merged.

**Closed by Dunbaratu** 2015-12-30 04:37 UTC
Labels: bug
