### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by marccardinal** [KSP-KOS/KOS#2087] opened 2017-08-12 01:54 UTC
I have been working on a script and during my tests have done several "Load Save..." to reset the state of my experimentation.

After several loads, it looks like a `runpath("0:/boot/myscript.ks").` gives me the following error at random points in my program. Here is one example of such error:

```
Object reference not set to an instance of an object
At (kOS built-in Update)
<<System Built-In Flight Control Updater>>
Called from 0:/boot/myscript.ks, line 102
    local t is pidRCS:update(time:seconds, relVelocity:normalized:z).
                                                                  ^
```

Questions:
* Is there a leak or something that happens when I re-load a save too many times?
* Doing a power cycle on the kOS part does not help and still results in random failures.
* Is there a workaround other than exiting to the main menu?

**Comment by marccardinal** [comment] 2017-08-12 03:58
Another more obscur example from loading a couple of times again:

```
Object reference not set to an instance of an object
At 0:/lib/move.ks, line 74
  lock steering to target:position.
  ^
Called from 0:/boot/myscript.ks, line 75
```

**Comment by hvacengi** [comment] 2017-08-15 01:29
This is probably caused by the same issue for #2051 which I'm currently working on.  I don't know that it's necessarily true, but highly likely.

Can you post a log file that goes along with this error if you're reproducing it reliably?  There should be an underlying error in the log next to the error you're seeing on the terminal.  That will confirm if it is the same error.

My goal in the fix is to catch the potential race condition where the parameter dictionary is null (I don't know what causes that race condition, it should not be possible).

**Comment by marccardinal** [comment] 2017-08-16 01:11
Good evening,

I would love to get you a log file but I can't seem to find them... where are they usually created?

**Comment by hvacengi** [comment] 2017-08-16 01:14
The easy one is "KSP.log" in the root of your KSP install, next to "KSP.exe".  Alternatively "output_log.txt" in the "KSP_Data" or "KSP_x64_Data" folder (or somewhere else for Linux/Mac) has more details, but shouldn't be necessary to see all of kOS's error data.

**Comment by marccardinal** [comment] 2017-08-16 01:58
Hopefully this helps:

```
[LOG 21:55:40.071] kOS: Pushing context staring with: File                 Line:Col IP   label   opcode operand
[LOG 21:55:40.073] kOS: Saving and removing 0 pointers
[LOG 21:55:54.140] kOS: FlightControl Binding
[LOG 21:55:54.141] kOS: FlightControl Bound
[LOG 21:55:54.629] kOS: FlightControlManager: ToggleFlyByWire: steering False
[LOG 21:55:54.631] kOS: FlightCtrlParam: Enabled: steering False => False
[LOG 21:55:54.632] kOS: FlightControlManager: ToggleFlyByWire: steering True
[LOG 21:55:54.634] kOS: FlightCtrlParam: Enabled: steering False => True
[LOG 21:55:54.635] kOS: FlightCtrlParam: toggle steering parameter
[LOG 21:55:54.642] kOS: At 0:/lib/dock.ks, line 89
  lock steering to lookdirup(target:position, v(0,1,0)).
  ^
Called from 0:/boot/main.ks, line 106
      DOCK_PointToward(targetDockingPort).
                       ^

[LOG 21:55:54.645] System.NullReferenceException: Object reference not set to an instance of an object
  at kOS.Module.kOSVesselModule.GetFlightControlParameter (System.String name) [0x00000] in <filename unknown>:0 
  at kOS.Binding.FlightControlManager+FlightCtrlParam.set_Enabled (Boolean value) [0x00000] in <filename unknown>:0 
  at kOS.Binding.FlightControlManager.ToggleFlyByWire (System.String paramName, Boolean enabled) [0x00000] in <filename unknown>:0 
  at kOS.Binding.BindingManager.ToggleFlyByWire (System.String paramName, Boolean enabled) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Execution.CPU.ToggleFlyByWire (System.String paramName, Boolean enabled) [0x00000] in <filename unknown>:0 
  at kOS.Function.FunctionToggleFlyByWire.Execute (kOS.SharedObjects shared) [0x00000] in <filename unknown>:0 
  at kOS.Function.FunctionBase.Execute (kOS.Safe.SafeSharedObjects shared) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Function.FunctionManager.CallFunction (System.String functionName) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Execution.CPU.CallBuiltinFunction (System.String functionName) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Compilation.OpcodeCall.StaticExecute (ICpu cpu, Boolean direct, System.Object destination, Boolean calledFromKOSDelegateCall) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Compilation.OpcodeCall.Execute (ICpu cpu) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Execution.CPU.ExecuteInstruction (IProgramContext context, Boolean doProfiling) [0x00000] in <filename unknown>:0 
[LOG 21:55:54.659] Code Fragment
File                 Line:Col IP   label   opcode operand
====                 ====:=== ==== ================================  
0:/lib/dock.ks         88:3   2695 @2675   push False 
0:/lib/dock.ks         88:3   2696 @2676   call toggleflybywire() 
0:/lib/dock.ks         88:3   2697 @2677   pop 
0:/lib/dock.ks         88:3   2698 @2678   push 2806 
0:/lib/dock.ks         88:3   2699 @2679   removetrigger 
0:/lib/dock.ks         88:3   2700 @2680   push $steering* 
0:/lib/dock.ks         88:3   2701 @2681   push 2506 
0:/lib/dock.ks         88:3   2702 @2682   store 
0:/lib/dock.ks         89:3   2703 @2683   push $steering* 
0:/lib/dock.ks         89:3   2704 @2684   pushdelegate 2493 
0:/lib/dock.ks         89:3   2705 @2685   storeglobal 
0:/lib/dock.ks         89:3   2706 @2686   push 2806 
0:/lib/dock.ks         89:3   2707 @2687   addtrigger 
0:/lib/dock.ks         89:3   2708 @2688   push _KOSArgMarker_ 
0:/lib/dock.ks         89:3   2709 @2689   push steering 
0:/lib/dock.ks         89:3   2710 @2690   push True 
0:/lib/dock.ks         89:3   2711 @2691   call toggleflybywire() <<--INSTRUCTION POINTER--
0:/lib/dock.ks         89:3   2712 @2692   pop 
0:/lib/dock.ks         90:1   2713 @2693   popscope 1 
0:/lib/dock.ks         90:1   2714 @2694   push 0 
0:/lib/dock.ks         90:1   2715 @2695   return 0 deep 
0:/lib/dock.ks         93:33  2716 dock_calcdistancetotgt`0-59106d6c pushscope 78 0 
0:/lib/dock.ks         94:13  2717 @2697   push localport 
0:/lib/dock.ks         94:13  2718 @2698   swap 
0:/lib/dock.ks         94:13  2719 @2699   storelocal 
0:/lib/dock.ks         94:24  2720 @2700   push targetport 
0:/lib/dock.ks         94:24  2721 @2701   swap 
0:/lib/dock.ks         94:24  2722 @2702   storelocal 
0:/lib/dock.ks         94:24  2723 @2703   argbottom 
0:/lib/dock.ks         96:31  2724 @2704   push _KOSArgMarker_ 
0:/lib/dock.ks         96:32  2725 @2705   push $localport 
0:/lib/dock.ks         96:43  2726 @2706   push $targetport 
0:/lib/dock.ks         96:54  2727 @2707   push position 
```

**Comment by hvacengi** [comment] 2017-08-16 02:50
Yeah, that looks like it's a related issue (but not exactly the same).  @Dunbaratu and I were just talking about some of the unusual things that Unity does that we have to take care of.  This should be fixed in the next release.

**Comment by marccardinal** [comment] 2017-08-16 13:13
Awesome! Thats great news :)

I am curious, what actually helped pinpoint the issue in the stacktrace?

**Closed** 2017-09-12 18:49 UTC
Labels: bug
