### ISSUE TITLE
ADDONS:RT:HASKSCCONNECTION returns false when ksc connection should be present

### ISSUE THREAD

**Issue by descention** [KSP-KOS/KOS#1538] opened 2016-03-13 03:43 UTC
Reference: http://imgur.com/LXqdox1

Made a small communication satellite network of two sats and one lander (has kerbals). Sat 1 in keostationary orbit, sat 2 near Mun. Lander near Sat 2. Lines on map show an active connection. Code says I'm not connected. Note, Sat 1 has dish pointed to active vessel (lander currently) and Sat 2 has dish pointed to Sat 1.

**Comment by Dunbaratu** [comment] 2016-03-13 06:31
Maybe the suffix could be named better but I think it means "has connection directly to KSC in a single hop" rather than "has a relayed connection to KSC thought multiple hops".  I think to just find if it has a connection *at all* it's `hasconnection` (remove the word 'ksc' in the middle).

I could be wrong, but I think that's what it means.  This isn't normally the area of the mod I work in.

**Comment by descention** [comment] 2016-03-13 16:36
It could be an issue on the end of the remote tech API. The link below is the function kos references. https://remotetechnologiesgroup.github.io/RemoteTech/modders/api/#bool-apihasconnectiontokscguid-id

**Comment by descention** [comment] 2016-03-13 17:41
I think my issue may be related to adding a KOS core to the lander pod, by means of module manager, without adding a flight computer. I'm still looking into it.

**Comment by descention** [comment] 2016-03-14 03:59
I think I figured it out. The vessel seems to require a Signal Processor (ModuleRemoteTechSPU) to get the Flight Computer. Without the flight computer, you can't connect to the KSC.

**Comment by descention** [comment] 2016-03-14 13:00
Did you edit my own comment to respond to me?

**Comment by descention** [comment] 2016-03-14 13:55
Also, yes. I can control the craft as normal with the kerbals on board. The KOS processor can still interact with the ship. To test this, make a vessel with a command pod (without signal processor), antenna, and KOS processor. You should be able to control the vessel until the kerbal leaves, at which point you have no connection.

**Comment by Dunbaratu** [comment] 2016-03-14 18:48
Sorry about editing your comment.  Github annoyingly has no "quote" button but does have an edit button right where the quote button should be (if you have the privileges) and so I make that mistake a lot.

**Comment by hvacengi** [comment] 2016-03-14 18:50
And for some reason github doesn't include comment history, even though the primary purpose of git is to keep track of history...

**Comment by Dunbaratu** [comment] 2016-03-14 18:50
My question about manual control wasn't about using the crew.  It was about using WASD from home base and not seeing the effect until signal delay happens, as opposed to using RT's flight computer.

**Comment by hvacengi** [comment] 2016-03-14 19:07
Is there any downside to us adding the SPU module to kOS processor parts?  Is there a reason that it would need to be installed on a probe core instead of any random part?

A patch we can probably include should be (but I didn't test it before sending this):
```
@PART[*]:AFTER[KOS]:NEEDS[RemoteTech]:HAS[!MODULE[ModuleSPU],MODULE[kOSProcessor]]
{
	%MODULE[ModuleSPU] { }
}
```

**Comment by descention** [comment] 2016-03-14 19:33
>
>`@PART[*]:AFTER[KOS]:NEEDS[RemoteTech]:HAS[!MODULE[ModuleSPU],MODULE[kOSProcessor]]
{
    %MODULE[ModuleSPU] { }
}`

This did not work. I still get no connection while sitting at KSC. May need to add ModuleCommand as per https://remotetechnologiesgroup.github.io/RemoteTech/modders/modules/#modulespu

**Comment by descention** [comment] 2016-03-14 19:44
I added the ModuleCommand to the snippet @hvacengi gave.
```
@PART[*]:AFTER[KOS]:NEEDS[RemoteTech]:HAS[!MODULE[ModuleSPU],MODULE[kOSProcessor]]
{
    %MODULE[ModuleSPU] { }
}
@PART[*]:AFTER[KOS]:NEEDS[RemoteTech]:HAS[!MODULE[ModuleCommand],MODULE[kOSProcessor]]
{
    %MODULE[ModuleCommand] { }
}
```
I have a connection, sorta. I can use the processor and it returns true for haskscconnection. I can't click the button on the right-click menu to open the terminal. It said no connection. I have to use the toolbar options, which worked just fine.

**Comment by Dunbaratu** [comment] 2016-03-14 19:45
Yeah that we can't do anything about. RemoteTech is very "rude" to other mods in that it takes over control of their context menus and disables them "for you".

**Comment by descention** [comment] 2016-03-14 19:48
That's fine with me, as I shouldn't need to click anything while I have a kos processor on the vessel.

**Comment by hvacengi** [comment] 2016-03-14 19:52
We won't be adding `ModuleCommand` to the kOS processor, since that turns the processor into a probe core which is not the intention.

I'm looking back over these details (I was out of town for the weekend and so I am just catching up).  If you need a SPU and on a command part, you need to add a probe core.  The nature of RT is that it always require that you have a probe core on board.  Whatever probe core you put on, look at the modules list in the VAB to verify it says "ModuleSPU" in the extended details (some cores from mods do not get the SPU) If you already have a probe core on board, this is a different issue.

If we need further troubleshooting, if the probe core isn't the fix, then we will need more information.  At the very least, we'll need a craft file to test locally.  Ideally we'll want a log file as well so that we can look for an error, but in the case of RemoteTech the error may be hidden.  It may even be easiest to send us a copy of your save file (and a list of mods).

If everything is working correctly, and if you have RT signal, the part menus should all be accessible.  If they are not accessible, there is some other issue and it may stem from a deeper RT issue.  I know that one of my friends has been having problems with satellites (without kOS) but I haven't had any time to try and help him troubleshoot.  We will want enough info on our end though to know that the issue isn't from kOS.

**Comment by descention** [comment] 2016-03-14 20:08
If I have to add a probe core to every vessel, that's fine. I'm trying to make sure the requirement is not a bug. Attached is the craft I'm testing with. I leave it landed on the pad for testing. It's just a pod, antenna, and kOS Processor. I expected to have haskscconnection resolve to true with just those. If I have to make changes to my ships, no problem.

[Pod+Radio+kOS.zip](https://github.com/KSP-KOS/KOS/files/172772/Pod.Radio.kOS.zip)

**Closed** 2016-03-14 20:09 UTC

**Comment by hvacengi** [comment] 2016-03-14 20:21
The deal is that we don't want to dramatically change the RT dynamic, nor the stock dynamic.  I'm actually surprised that the ship claims to have signal via the map drawn lines, if the RT api tells us it doesn't have a connection.  If that's the case, we should probably ask RT to not indicate that the ship has signal via the gui.  I would be curious to know if the ship without a probe core can still serve as a relay for signal, even though it can't actually do anything with it.

Adding the SPU to each command pod might make your existing design work, I hadn't thought of that.

**Comment by descention** [comment] 2016-03-14 20:41
>I would be curious to know if the ship without a probe core can still serve as a relay for signal, even though it can't actually do anything with it.
Just tested and they can. KSC <> Pod <> Pod <> Probe

Both pods had one omni antenna and a solar panel. I could control the probe still.

**Comment by hvacengi** [comment] 2016-03-14 20:53
Interesting.  So that explains why the lines remain on the map, because they're still useful.  Reading through the link you sent earlier, it looks like the antennae have a passive module that enables that relay functionality.
