### ISSUE TITLE
kOS returns one engine as two same ID and stage

### ISSUE THREAD

**Issue by andrey-zakharov** [KSP-KOS/KOS#1057] opened 2015-06-05 14:32 UTC
list engines.

ID          Stage   Name
------------------------------------------------
4291603492  0       ModuleEnginesFX
4291603492  0       ModuleEnginesFX

https://www.dropbox.com/s/h8puvpqwu8txkoy/quicksave.7z?dl=0

**Comment by andrey-zakharov** [comment] 2015-06-05 15:54
as result TWR calculates wrong and some of scripts cannot fly.

**Comment by hvacengi** [comment] 2015-06-05 18:40
The first is a duplicate of issue #1026 (which I thought I fixed, but apparently I never sent a pull request, will be sending that shortly)

The second is a duplicate of #940 and will be fixed with the next release (fixed in the develop branch).

In both cases, if you test it with various engines, you'll find that some don't show this issue.  That's because ModuleEnginesFX was updated to inherit from ModuleEngines.  In previous versions of KSP the PartModule only could be one or the other.  Now anything that is ModuleEnginesFX is also ModuleEngines (but not vice versa).

If you compile the most recent develop branch, you should be able to get ships with the "fancy" engines to fly.

**Closed** 2015-06-20 18:41 UTC
