### ISSUE TITLE
kOS unable to lock throttle or steering after undocking

### ISSUE THREAD

**Issue by ozin370** [KSP-KOS/KOS#1205] opened 2015-10-22 08:42 UTC
Was asked by hvacengi to post this issue as a reminder.

After docking and then undocking without ending a kOS program, the core is left unable to lock throttle or steering. Even ending the program and trying to lock throttle or steering manually does not work, only rebooting the core "fixes" the issue. Something related to the FlightControlManager according to hvacengi.

**Comment by ozin370** [comment] 2015-10-22 09:27
from the debug console:

[Log]: kOS: FlightControlManager: ToggleFlyByWire: throttle True
[Error]: no such flybywire parameter throttle

**Comment by hvacengi** [comment] 2015-10-22 13:04
It looks like the issue may be that the parameters are being released in `UnbindUnloaded` and are not being restored until the cpu boots and calls `shared.BindingMgr.Load()`.  I've modified the code to re-add any missing parameters after the default behavior of updating the vessel data.

@ozin370 I won't have much opportunity to test today, can you download this zip file and test with your code?
https://dl.dropboxusercontent.com/u/19195825/kOS/Debug-issue-1205.zip

**Comment by ozin370** [comment] 2015-10-22 14:41
I just tested it and that seems to have fixed the issue :)

**Comment by erendrake** [comment] 2015-10-22 14:56
@ozin370 great news :) we are ramping up for the next release soon

**Comment by hvacengi** [comment] 2015-10-22 15:42
What issue is this a duplicate of?  And I haven't sent the PR for this fix yet either.  I did a quick compile to see if it fixed it, but the fix isn't part of the develop branch yet as far as I'm aware.

**Comment by erendrake** [comment] 2015-10-22 17:53
just some overeager house cleaning. sorry about that

**Closed** 2015-11-13 06:15 UTC
Labels: bug
