### ISSUE TITLE
lock steering with just control surfaces

### ISSUE THREAD

**Issue by konelav** [KSP-KOS/KOS#1183] opened 2015-10-04 19:27 UTC
I tried to make very simple cruise missle (with Remote Tech) and realised that "lock steering" seems to have no effect at all with SAS turned off. My missle is very simple, actually it can be just any kOS processor, solid-fuel booster and x4 any control surfaces. With SAS ON lock steering works just as fine as SAS is (not very good).
Then I placed in my 6-tonn missle small inline reaction wheel, which should be completely useless on the altitudes ~100m, velocities 400+m/s and FAR mod. And now "lock steering" works fine without SAS. It looks like kOS does not even try to control attitude of aircraft when there is only control surfaces on it and no reaction wheels/RCS/...

**Comment by erendrake** [comment] 2015-10-04 20:05
I believe this is a dupe of other issues we have logged before. @hvacengi would you care to weigh in?

**Comment by hvacengi** [comment] 2015-10-07 17:47
You're right, this is a duplicate of the various other steering comments.  It is slightly different in that the new steering code does not do any predictions to account for aerodynamic control surfaces.  The short explanation of that decision is essentially that squad does not provide a quick and easy method to get that data, and to calculate it ourselves is essentially doing the aerodynamic calculations a 2nd time in the physics tick.  

What I have done is set up the steering code so that it adapts the "available" torque according to observations in the simulation.  I just now ran a test using a probe core with tail fins and no reaction wheel or gimbal.  The initial roll to orient the top vector to the west while ascending straight up was a little rough.  But the remainder of my ascent curve was quite smooth (pitch down 1.75° from vertical and then following surface prograde).  The only issues popped up once I was too high to get accurate 

As I understand it, FAR makes it possible to get better data, but not being familiar with FAR I did not want leaning a 2nd version of aerodynamics to slow the release of the improved steering.  And I can say with confidence that this new code is much more robust than our previous code.  It's possible that the adaptive torque will work with FAR too, but I have not tested it.  I'm planning on releasing some demo videos showcasing the new steering, and I'll make sure to include this scenario (sans FAR) in those videos.  I'll also link to them here when I do.

**Closed** 2015-11-05 20:07 UTC
Labels: duplicate
