### ISSUE TITLE
Running some precompiled scripts causes internal error during relabeling

### ISSUE THREAD

**Issue by MaxRebo1** [KSP-KOS/KOS#1869] opened 2016-11-18 20:27 UTC
(for more context, see the [KSP forum post](http://forum.kerbalspaceprogram.com/index.php?/topic/61827-113-kos-scriptable-autopilot-system-v101-20161011/&page=184#comment-2855587))
In KSP v1.2.1, using kOS version 1.0.2-pre-2, the following constellation of two scripts works if _bar_src.ks_ is run directly, but fails with an error when using its precompiled form _bar.ksm_:

**[foo.ks](https://github.com/KSP-KOS/KOS/files/600848/foo.txt)**
**[bar_src.ks](https://github.com/KSP-KOS/KOS/files/600851/bar_src.txt)**

Running _foo.ks_ results in the following error:
```
[LOG 19:33:08.260] kOS: At [built-in], line 0
Called from 1:/foo, line 9
		RUNPATH(_lib).
		  ^
Called from 1:/foo, line 37
SET bar_compiled TO import("bar").
                           ^
[LOG 19:33:08.261] kOS.Safe.Exceptions.KOSCompileException: ProgramBuilder.ReplaceLabels: Cannot add label throttle`0-2f3c6c7a, label already exists.  Opcode: pushscope 16 15
  at kOS.Safe.Compilation.ProgramBuilder.ReplaceLabels (System.Collections.Generic.List`1 program) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Compilation.ProgramBuilder.BuildProgram () [0x00000] in <filename unknown>:0 
  at kOS.Safe.Execution.ProgramContext.AddObjectParts (IEnumerable`1 parts, System.String objectFileID) [0x00000] in <filename unknown>:0 
  at kOS.Function.FunctionLoad.Execute (kOS.SharedObjects shared) [0x00000] in <filename unknown>:0 
  at kOS.Function.FunctionBase.Execute (kOS.Safe.SafeSharedObjects shared) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Function.FunctionManager.CallFunction (System.String functionName) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Execution.CPU.CallBuiltinFunction (System.String functionName) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Compilation.OpcodeCall.StaticExecute (ICpu cpu, Boolean direct, System.Object destination, Boolean calledFromKOSDelegateCall) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Compilation.OpcodeCall.Execute (ICpu cpu) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Execution.CPU.ExecuteInstruction (IProgramContext context, Boolean doProfiling) [0x00000] in <filename unknown>:0 
[LOG 19:33:08.270] Code Fragment
File                 Line:Col IP   label   opcode operand
====                 ====:=== ==== ================================  
                        0:0   0000         jump +155 
[built-in]              0:0   0001 @LR00   pushscope -999 0 
[built-in]              0:0   0002 @LR01   push $runonce 
[built-in]              0:0   0003 @LR02   swap 
[built-in]              0:0   0004 @LR03   storelocal 
[built-in]              0:0   0005 @LR04   push $filename 
[built-in]              0:0   0006 @LR05   swap 
[built-in]              0:0   0007 @LR06   storelocal 
[built-in]              0:0   0008 @LR07   push _KOSArgMarker_ 
[built-in]              0:0   0009 @LR08   push $filename 
[built-in]              0:0   0010 @LR09   eval 
[built-in]              0:0   0011 @LR10   push True 
[built-in]              0:0   0012 @LR11   push null 
[built-in]              0:0   0013 @LR12   call load() <<--INSTRUCTION POINTER--

 ...

[LOG 19:33:08.307] kOS: Stack dump: stackPointer = 5
010      SubroutineContext: {CameFromInstPtr 239, TriggerPointer -1} (type: SubroutineContext)
009      kOS.Safe.Execution.VariableScope (type: VariableScope)
          ScopeId=1, ParentScopeId=0, ParentSkipLevels=1 IsClosure=False
            local var $_lib is String with value = bar
008      kOS.Safe.Execution.VariableScope (type: VariableScope)
          ScopeId=2, ParentScopeId=1, ParentSkipLevels=1 IsClosure=False
007      SubroutineContext: {CameFromInstPtr 50, TriggerPointer -1} (type: SubroutineContext)
006      kOS.Safe.Execution.VariableScope (type: VariableScope)
          ScopeId=-999, ParentScopeId=0, ParentSkipLevels=1 IsClosure=False
            local var $runonce is Boolean with value = False
            local var $filename is String with value = bar
005 SP-> _KOSArgMarker_ (type: KOSArgMarkerType)
004      _KOSArgMarker_ (type: KOSArgMarkerType)
003      _KOSArgMarker_ (type: KOSArgMarkerType)
002      $bar_compiled (type: String)
001      _KOSArgMarker_ (type: KOSArgMarkerType)
000      0 (type: Int32)

[LOG 19:33:08.309] kOS: Popping context 2
```
(full [KSP.log](https://github.com/KSP-KOS/KOS/files/600876/KSP.log.txt))

Attached save file [kOS.zip](https://github.com/KSP-KOS/KOS/files/600890/kOS.zip) has a vessel called "kOS Tester" in orbit, which has the _foo.ks_ and _bar_src.ks_ files from above loaded on the local volume of its sole CPU.`RUN foo.`to reproduce.

**Comment by hvacengi** [comment] 2016-11-18 22:48
I took a little time to test this out, and it appears that the issue is arising from the identical throttle lock statements coincidentally having identical scope identifiers.  When compiling the program to ksm, a blank context is used as a placeholder, so the ksm file starts with a fresh scope ID to match.  For most pieces of code it doesn't matter much, because the contents of most functions don't get replicated identically.  But `lock throttle to 0.` is a very common command, and as such it has the opportunity to have a collision more frequently.

This does have a potentially more complicated result, if the duplicated scope id's mean that these ksm functions are "stealing" a scope from another function.  I haven't had much time to look into that aspect of the issue yet, but will continue to investigate tonight.  It might end up being a good thing for @Dunbaratu to look at since he knows the VM logic much better than I do.

**Comment by Dunbaratu** [comment] 2016-11-18 23:20
Right now the logic to identify "I am a different function than that function over there" to guarantee uniqueness is done using a hash of the compiled statements.  Then there's a hash table lookup to map from "chunk of code" to "name of function" when compiling.

The problem is when there's two identical ones like this, and how "LOCK" is really a function so two 'lock throttle to 0` instances are two of the same function then.  The system worked fine when all we had was global vars and no scoping.  Then you honestly don't care that the wrong function got called because the whole point is that they both do the same thing so who cares which you call.  But when scoping was added the fact that two identical looking functions are really located in two different places matters because the functions carry their closure contexts with them.

The fix may be as simple as encoding location information into the hash so the same function located in two different places still counts as two different distinguishable functions.

**Comment by MaxRebo1** [comment] 2016-11-18 23:21
That's good to know. The obvious workaround then is to encapsulate`LOCK THROTTLE TO 0`in a function and always call that, which seems to get rid of the error for me even in the much more complex scripts where it first manifested. I can live with that until you decide on a fix.

**Comment by Dunbaratu** [comment] 2016-11-18 23:24
I can't get to this now but I'd like to look at it tomorrow morning (thus why I self-assigned it).

**Closed** 2016-11-23 02:26 UTC
