### ISSUE TITLE
disabling verbose logging shows "contact devs" on some exception types

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#735] opened 2015-04-05 06:37 UTC
![screenshot4](https://cloud.githubusercontent.com/assets/11031560/6996031/381296f4-db77-11e4-9bbd-9f734b60ea6f.png)
found this while testing that: #732

**Comment by Dunbaratu** [comment] 2015-04-05 06:42
Are you saying turning verbose on fails to STOP saying "contact devs"? If so that's not a bug.  Whether it says "contact devs" or not should be the *same* whether doing verbose or terse logging.

Or are you saying turning on verbose causes errors to START saying "contact devs" when they previously didn't?  If so that would be important.

**Comment by abenkovskii** [comment] 2015-04-05 06:52
No: exactly oposite to the first variant: turning on vrebose actually stops "contact devs" message. Originally I even thought that terse logging is causing "contact devs" exception. But division by 0 and missing `.` messages are not causing "contact devs" no matter if verbose is on or off.

**Comment by abenkovskii** [comment] 2015-04-05 06:57
[output_log](https://www.dropbox.com/s/ibt4pprx91ew3vc/output_log.txt?dl=0)

**Comment by abenkovskii** [comment] 2015-04-09 16:57
And now I see this bug #676 with verbose logging too:
![screenshot2](https://cloud.githubusercontent.com/assets/11031560/7072062/1f105640-def2-11e4-9a14-5b5c289ec67b.png)
log: https://www.dropbox.com/s/o2g32xc5s171vll/output_log_ecxeption_in_error_description.txt?dl=0

**Comment by Dunbaratu** [comment] 2015-09-09 02:14
I gave up on trying to reproduce this problem ages ago.  It just doesn't happen.

**Comment by Dunbaratu** [comment] 2015-09-09 02:16
Closing as "invalid" when what I really mean is "moot", which isn't quite the same thing, but we don't have a "moot" label.  It means "I'm not saying this was never a bug.  I'm saying it doesn't seem to be a bug *anymore*".

**Closed by Dunbaratu** 2015-09-09 02:16 UTC
Labels: bug, invalid
