### ISSUE TITLE
Can't unlock throttle inside until

### ISSUE THREAD

**Issue by kendoka15** [KSP-KOS/KOS#1051] opened 2015-05-28 17:48 UTC
I've tried many ways and I can't ever seem to unlock the throttle from an until.

(Test code: http://pastebin.com/Z5ZfD5x3 )

**Comment by space-is-hard** [comment] 2015-05-28 21:33
May be related to #1048

**Comment by Dunbaratu** [comment] 2015-05-28 23:26
Duplicate of #1048 - since it occurs with *any* ``unlock throttle`` that occurs inside a brace section.

**Closed** 2015-05-28 23:27 UTC
Labels: duplicate
