### ISSUE TITLE
Terminal window not opening

### ISSUE THREAD

**Issue by eubanks718** [KSP-KOS/KOS#2486] opened 2019-04-11 18:17 UTC
Hi, 
Running KSP v1.7 and kOS 1.1.7.0.
Just noticed with the latest KSP update that the terminal window is no longer having a display on the screen. This occurs on both the Windows and the OSX version of the game. Have tried different resolutions and different save files & ships with no effect.

Some general things I have noticed: I can click in the general area that the terminal window should be and it does take the focus away from the main game play window. Typing commands in the "invisible terminal window" does not result in any action (such as typing SAS OFF.).

Below are the additional mods I am running.
<img width="673" alt="Screen Shot 2019-04-11 at 2 15 39 PM" src="https://user-images.githubusercontent.com/49533342/55981299-5095f280-5c64-11e9-9759-6684eeb14e52.png">

**Comment by eubanks718** [comment] 2019-04-12 16:55
Just to update. When I open the KSP console, clicking on the terminal icon gives the error message "Exception: ArgumentOutOfRangeException: Argument is out of range. Parameter name: Index"

**Comment by Dunbaratu** [comment] 2019-04-12 23:36
Do you have the rest of the error log surrounding that message?  There should be a trace of where it occurred in the program.

**Comment by Dunbaratu** [comment] 2019-04-12 23:45
Ooh, an idea just occurred to me:
When you look in GameData/kOS/GFX/ do you see two copies of all the image files, one copy with extension ".png" and the other with extension ".dds"?

**Comment by eubanks718** [comment] 2019-04-13 00:36
Only had one set of images. So I wiped the entire kOS folder and reinstalled it and no effect. 

Upon loading into a vessel, I see the error message "Error: Module kOSProcessor threw during OnStartFinished: System.NullReferenceException: Object reference not set to an instance of an object
   at PartModule.ApplyAdjustersOnStart () [0x00000] in <filename unknown>:0
   at Part.ModulesOnStartFinished () [0x00000] in <filename unkown>:0"
not sure if that is related

The other error message I posted previously happens right after "kOS: Open window by event"

Thats all the information I see from the console, not sure if there is another place to look.

**Comment by Dunbaratu** [comment] 2019-04-13 01:23
Can you paste the whole error log file?  I need more information on the full trace and what happened before and after that part.

**Comment by eubanks718** [comment] 2019-04-13 13:17
[KSP.log](https://github.com/KSP-KOS/KOS/files/3076210/KSP.log)

Here is a log file. For the session I opened up a sandbox save where I had a vessel with a processor on the launchpad. I loaded the vessel and tried to open up the terminal window. Hope this helps. Let me know if you need anything else.

**Comment by Dunbaratu** [comment] 2019-04-14 01:21
I do not know the cause yet, but another person on Discord reported the same problem and your log file and their log file share a lot of common things so I think you have the same problem.

Notibly, you are on Mac, with OpenGL.  The other person is on Windows with DirectX.  You don't have the same graphics card either, so none of this is a platform issue.  Your platforms are as different as can be yet you have the same problem.

This error message is all over the log for both of you:
```
[EXC 09:09:56.340] ReflectionTypeLoadException: The classes in the module cannot be loaded.
```
kOS gets this error as do several other mods. Kerbal Wind Tunnel is the first mod to show this problem, and both you and the other person have that mod in common.

I still can't find the problem, but that error message seems to be the main culprit.  Several mods that try to do the "reflection" call ``GetTypes()`` in a way similar to what kOS is trying to do, are hitting the same wall in both of your installations.

**Comment by Dunbaratu** [comment] 2019-04-14 01:32
Can you try this test for me?

Make an installation of KSP in which kOS is the *ONLY* mod present, with nothing else installed.

See if you get the same problem.  If not, then we at least know whether interactions with other mods are the right or wrong idea to pursue.

**Comment by Dunbaratu** [comment] 2019-04-14 01:37
Update: The other person on discord reports that removing the Kerbal Wind Tunnel mod completely fixed the problem.
There may be issues to raise to the maintainer of Wind Tunnels - it may be that just recompiling the mod might help?

**Comment by Dunbaratu** [comment] 2019-04-14 01:59
@eubanks718 - Can you confirm for me if removing the Wind Tunnel mod fixes the issue for you like it did for @austinjames314 ? If it does, then I'll close the issue here and I guess throw the problem over to Wind Tunnel.

**Comment by eubanks718** [comment] 2019-04-14 03:41
So uninstalling Wind Tunnel did fix it. Bizarre that these two mods would interact.

**Comment by Dunbaratu** [comment] 2019-04-14 04:06
It's not that they interact.  They don't.
It's that Wind Tunnel contains a DLL file that is not compatible with Reflection calls in the version of Mono that KSP uses, and some mods (kOS included) attempt to use reflection to iterate over all the types that exist.  When they do that, they bomb out when the system hits the stuff loaded by the one DLL that isn't the right version.

**Closed** 2019-04-14 04:07 UTC
Labels: wontfix

**Comment by Dunbaratu** [comment] 2019-04-20 10:04
Actually it's becoming a problem with another mod, not just Wind Tunnel, so I think I'll have to find a way around it. I opened a new issue about it, here:  #2491
