### ISSUE TITLE
Adding a "CountDown" structure

### ISSUE THREAD

**Issue by Efratror** [KSP-KOS/KOS#1797] opened 2016-08-30 18:04 UTC
I would like to have some structure that is formatted like `TimeSpan`(with all it's suffixes) but is settable so you can use it to make a count down of x seconds. I first built a function in kOS to do this, but as you warp the code block isn't small enough for kOS to update it every second and it hangs.

PS. here's the code I used. 

```
FUNCTION CountDown {
    Parameter timeUnit.

    LOCAL hourZero   TO "".
    LOCAL minuteZero TO "".
    LOCAL secondZero TO "".

    LOCAL hourFloor TO FLOOR(timeUnit/3600).
    LOCAL minuteFloor TO FLOOR((timeUnit-(hourFloor*3600))/60).
    LOCAL secondFloor to FLOOR(timeUnit-(hourFloor*3600)-(minuteFloor*60)).

    IF hourFloor < 10   {SET hourZero   TO "0".}    ELSE {SET hourZero   TO "".}
    IF minuteFloor < 10 {SET minuteZero TO "0". }   ELSE {SET minuteZero TO "".}
    IF secondFloor < 10 {SET secondZero TO "0". }   ELSE {SET secondZero TO "".}

    LOCAL TimeUnit TO hourZero+hourFloor+":"+minuteZero+minuteFloor+":"+secondZero+secondFloor.
    RETURN TimeUnit.
}
```

**Comment by TDW89** [comment] 2016-08-30 18:17
Um why not use something like:
```
set dt to 10.
set targetTime to time + dt.

until done {
    print (targetTime - time):clock.
}.
```

**Comment by hvacengi** [comment] 2016-08-30 19:55
I guess the question is whether or not you're trying to make a timer that automatically counts down to zero, or if you just want to expose the timespan formatting information.  #183 already identifies the need for a timespan constructor, but that would be a dumb structure that doesn't automatically update.

>but as you warp the code block isn't small enough for kOS to update it every second and it hangs.

Do you mean that it takes more than one tick to update, which is a problem, or are you referring to the larger time delta between frames during timewarp?  The first can be fixed by increasing `config:ipu`.

As @TDW89 points out, it is an undocumented feature that you can add `Scalar` and `TimeSpan` structures and the return value will be a `TimeSpan`.  Which means you can take advantage of that to make your own formatter:

```
function countdown {
    parameter dt.
    local endUt is time + dt. // timespan + scalar = timespan
    return { // use an anonymous function to keep local scope
        return endUt - time.
    }
}

set cd to countdown(10).
wait 1.
print cd:second. // should print "9"
wait until cd:seconds < 0.
print cd:seconds. // should print a value less than 0
```
_Disclaimer: untested code.  I think it works.  I could be wrong_

**Comment by Efratror** [comment] 2016-08-30 20:30
@TDW89 Thank you for your solution, if been blinded by the fact i couldn't shorten my code. While i used the undocumeted feature of adding a `Scalar` to a `TimeSpan` structure.

the code you both provided is a nice work around for a automatic count down timer, which would be a wonderful addition to kOS for displaying time until an event (docking, launch, ending of warp to a certain point.)

@hvacengi i tried increasing the ipu, but even at 2000 (it's maximum amount) it freezes the printing of the countdown after setting warping past 50x so the larger time delta between frames is the problem.

**Comment by Efratror** [comment] 2016-08-31 23:45
Have been playing a bit with it to day and when you change the anonymous function to a function with a name and return that function afterwards it works

**Comment by TDW89** [comment] 2016-09-01 12:51
@Efratror this should fix it for you.
(couple of typos and changed `cd:seconds` to `cd:call:seconds`)

```
function countdown {
    parameter dt.
    local endUt is time + dt. // timespan + scalar = timespan
    return { // use an anonymous function to keep local scope
        return endUt - time.
    }.
}.

set cd to countdown(10).
wait 1.
print cd:call:seconds. // should print "9"
wait until cd:call:seconds < 0.
print cd:call:seconds. // should print a value less than 0

**Comment by hvacengi** [comment] 2016-09-01 13:12
Oh yeah, the delegate object gets returned instead of called in that case. It would probably work as `cd():seconds` too

**Comment by TDW89** [comment] 2016-09-01 13:14
@hvacengi just creating an issue for that `cd():typename` is `scalar` !?!?

**Comment by Dunbaratu** [comment] 2016-10-01 01:38
Is this issue pretty much done and should be closed?  If I read this right the only remaining thing in the issue is the fact that the identifier name ``cd`` caused confusing results.  That issue is now covered in #1798.  The issue the title talks about, about adding a countdown structure, was handled in the comments with an alternate solution.

**Comment by Efratror** [comment] 2016-10-01 01:59
If you don't plan to make a structure or a build-in function for a countdown system tis issue is fixed and should be closed.

**Closed** 2016-12-28 20:25 UTC
Labels: enhancement
