### ISSUE TITLE
'impossible FromPrimitiveWithAssert(<null>) was attempted'

### ISSUE THREAD

**Issue by pellinor0** [KSP-KOS/KOS#1961] opened 2017-02-24 17:24 UTC
relevant parts of the log:
http://pastebin.com/0iuqPCzU

These are the scripts used:
https://github.com/pellinor0/kOS-MissionFramework/tree/e472aeee7a30df708131aa2f6166ea6d1384d43a
where the log mentions "1:/mission.ks", it refers to the file Script/missions/m_ast.ks

This happened on a kOS processor with a boot file after jumping to a ship. Rebooting fixed the issue and the script ran fine the second time. I have also reproduced it after loading the scene as a quicksave and starting the processor manually. 

In this install I also get other sporadic errors from kOS when bootfiles are executed right after quickloading and the vessel has maneuverNodes and a Target (I still have to reproduce those in a cleaner environment). I'm reporting this one because it looks more severe and did not happen before.

**Comment by hvacengi** [comment] 2017-02-24 19:10
How fast after booting does the script execute?  If the target has not yet updated it's orbit to find the next patch, the underlying patch itself is null which would make this a duplicate of #1651 because we don't do a null check.  Can you try checking `hasnextpatch` before accessing it (which is a good practice regardless of the timing of execution)?

**Comment by pellinor0** [comment] 2017-02-25 23:58
It looks like both setting the target and accessing its orbit were happening in the same frame. Adding a "wait 0." between those calls prevents the error. 

So the issue is resolved from my side, feel free to close unless you want to keep a reminder about the internal error.

**Closed** 2017-05-10 04:16 UTC
Labels: Error Messages
