### ISSUE TITLE
[1.2] kOS causes immese amounts of game lag looking for Infernal Robotics

### ISSUE THREAD

**Issue by NCommander** [KSP-KOS/KOS#1855] opened 2016-10-25 08:37 UTC
After about 20-30 minutes of game play, I start getting massive amounts of game lag, and debug spam. Game log attached, but here are the revelant bits, IR is not installed on this copy of KSP 1.2.
```
[EXC 03:36:31.513] NotSupportedException: The invoked member is not supported in a dynamic module.
	System.Reflection.Emit.AssemblyBuilder.GetExportedTypes ()
	kOS.AddOns.InfernalRobotics.IRWrapper+<>c.<InitWrapper>b__39_0 (.LoadedAssembly a)
	System.Linq.Enumerable+<CreateSelectIterator>c__Iterator10`2[AssemblyLoader+LoadedAssembly,System.Type[]].MoveNext ()
	System.Linq.Enumerable+<CreateSelectManyIterator>c__Iterator12`2[System.Type[],System.Type].MoveNext ()
	System.Linq.Enumerable.First[Type] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback)
	System.Linq.Enumerable.FirstOrDefault[Type] (IEnumerable`1 source, System.Func`2 predicate)
	kOS.AddOns.InfernalRobotics.IRWrapper.InitWrapper ()
	kOS.AddOns.InfernalRobotics.IRHandler.FixedUpdate ()
```

and then repeating variants of this log spam:

```
[LOG 03:36:32.749] 10/25/2016 3:36:32 AM,kOS-IRWrapper,Attempting to Grab IR Types...
[EXC 03:36:32.753] NotSupportedException: The invoked member is not supported in a dynamic module.
	System.Reflection.Emit.AssemblyBuilder.GetExportedTypes ()
	kOS.AddOns.InfernalRobotics.IRWrapper+<>c.<InitWrapper>b__39_0 (.LoadedAssembly a)
	System.Linq.Enumerable+<CreateSelectIterator>c__Iterator10`2[AssemblyLoader+LoadedAssembly,System.Type[]].MoveNext ()
	System.Linq.Enumerable+<CreateSelectManyIterator>c__Iterator12`2[System.Type[],System.Type].MoveNext ()
	System.Linq.Enumerable.First[Type] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback)
	System.Linq.Enumerable.FirstOrDefault[Type] (IEnumerable`1 source, System.Func`2 predicate)
	kOS.AddOns.InfernalRobotics.IRWrapper.InitWrapper ()
	kOS.AddOns.InfernalRobotics.IRHandler.FixedUpdate ()
[LOG 03:36:32.758] 10/25/2016 3:36:32 AM,KerbalAlarmClock,Setting App Button True
[LOG 03:36:32.768] [PlanetariumCamera]: Focus: Jebediah Kerman
[LOG 03:36:32.815] 10/25/2016 3:36:32 AM,kOS-IRWrapper,Attempting to Grab IR Types...
[EXC 03:36:32.819] NotSupportedException: The invoked member is not supported in a dynamic module.
	System.Reflection.Emit.AssemblyBuilder.GetExportedTypes ()
	kOS.AddOns.InfernalRobotics.IRWrapper+<>c.<InitWrapper>b__39_0 (.LoadedAssembly a)
	System.Linq.Enumerable+<CreateSelectIterator>c__Iterator10`2[AssemblyLoader+LoadedAssembly,System.Type[]].MoveNext ()
	System.Linq.Enumerable+<CreateSelectManyIterator>c__Iterator12`2[System.Type[],System.Type].MoveNext ()
	System.Linq.Enumerable.First[Type] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback)
	System.Linq.Enumerable.FirstOrDefault[Type] (IEnumerable`1 source, System.Func`2 predicate)
	kOS.AddOns.InfernalRobotics.IRWrapper.InitWrapper ()
	kOS.AddOns.InfernalRobotics.IRHandler.FixedUpdate ()
```
[KSP.zip](https://github.com/KSP-KOS/KOS/files/550040/KSP.zip)

**Comment by hvacengi** [comment] 2016-10-25 10:47
Duplicate of #1849.  I don't know if you have ContractConfigurator installed or if it's another mod causing the same error, but it is the same error.

**Closed** 2016-10-25 10:48 UTC
Labels: duplicate
