### ISSUE TITLE
Anonymous functions break with `lock steering`

### ISSUE THREAD

**Issue by Gotbread** [KSP-KOS/KOS#1784] opened 2016-08-21 20:12 UTC
I have a function framework consisting of

-a boot file, which copies the start script from the archive:
http://pastebin.com/jyg22Bj8 in /boot/mission.ks
-a mission file based on the crafts name:
http://pastebin.com/SvPEQDDt in /Mission/StationCore.mission.ks
-and some librarys which supplys all the functions:
http://pastebin.com/sKpzDnP0 /Mission/mission_runner.ks
http://pastebin.com/rYbbNzyn /Mission/Functions/Utility.ks

I am using this setup for some time now. But suddenly, it failed with the error:
![koserr1](https://cloud.githubusercontent.com/assets/19180639/17839608/860fb176-67ed-11e6-8095-a3cae2790407.png)
and:
![koserr2](https://cloud.githubusercontent.com/assets/19180639/17839610/8b8fc172-67ed-11e6-9b1f-717a18a04b58.png)

Relevant lines are in mission.ks @ 77-78
I try to get the target file name, download it into local volume and run it. Which worked fine,
but now i keep getting this error message. I added the print line @77 just in case it was using
the wrong name, but as seen in the screenshots, the name matches up. When i list the files,
the file is there but i cannot run it, not even manually.

At the point where it started crashing i was changing things in Utility.ks. The only thing i noted
was that the file grew bigger then the 40kb mark imposed by the smaller core. However i was
using the bigger KAL-9000 core for the whole time to avoid this issue. I even increased the
volume size in the VAB but the same error occured, so the file size might be unrelated. I did
not change anything in mission.ks or in StationCore.mission.ks at the time of the first crash.

Even after restarting the error persists. The file gets copied into the volume but i cannot run it.

**Comment by Dunbaratu** [comment] 2016-08-21 23:45
Do you have the KSP output log showing the underlying error message?  It will contain a full trace of the stack that tells us which of our own methods it was crashing in.

**Comment by Gotbread** [comment] 2016-08-22 02:56
Here is the log output of a clean run: (started a fresh instance of ksp, loaded the craft, launched it, reverted to VAB, closed the game):
http://pastebin.com/RYSBDPVM
since the log is quite big, here are the relevant kos parts:
http://pastebin.com/GqRFxqm0

**Comment by Dunbaratu** [comment] 2016-08-22 04:59
Okay, there's a lot to break down there in how you're running things that run things that run things.

But it looks like the crash is specifically when it tries to run StationCore.mission.ks.  And one thing that might be interesting about that is that it has two dots in the filename.  I don't know if we ever tested for that case, but there is some manipulation we do to look for the filename extension that could be being done wrongly here.  I'm usually careful to make sure I always do such checks with an explicit "only the lastmost dot counts" logic in it (i.e. look for the dot from the end of the string instead of from the start specifically because of cases with more than one dot in the filename), but I didn't write everything in there so I'm not 100% sure how it all works and even if I did I can make mistakes.

Can you make a quick test where you name the file something without a dot (i.e. call it something like StationCore_mission.ks instead of StationCore.mission.ks.) and try this again to see if that makes it work?  If it does, then that tells us where exactly to look for the fix to the problem, and it would give you a workaround in the meantime.

**Comment by Gotbread** [comment] 2016-08-22 06:36
i tried with "StationCoremission.ks" instead of "Stationcore.mission.ks" but the same error still occures, with the same stack trace. When i try to run the file manually the error also occures.

I was careful at first but since it worked for all test cases, i kept using the extra dot. The strange thing is that i wasn't even working on the file in question.

**Comment by hvacengi** [comment] 2016-08-22 14:51
The most common source of program label "key not found" errors is an attempt to call a function that does not exist.  We don't provide a good error message for this case (I think there's an issue for this already) so it doesn't really help you narrow down the cause of the error.  By adding a detailed exception, I narrowed down your issue to line 22 of `StationCore.mission.ks`, specifically the reference to steering.  It would appear that there is an issue locking steering from within an anonymous function.  I pulled the steering code into a named function instead and the script loaded (with other errors about unexpected tokens which I will leave to you to troubleshoot).  So if you instead do this:

```
function LockSteering {
	lock steering to -ship:velocity:surface.
}
```
and reference it as `LockSteering@` in the sequence list (line 22) it should work.

**Comment by Gotbread** [comment] 2016-08-22 16:51
Just tried it and indeed it works.

**Comment by hvacengi** [comment] 2016-08-22 16:53
Renaming the issue to be more in line with the actual error.

**Comment by Dunbaratu** [comment] 2016-08-22 20:51
What?  There was a bug with anonymous functions not having proper scope, which this might be an instance of, but I thought that fix was already in the release.  Maybe there's another problem elsewhere with them.

**Comment by hvacengi** [comment] 2016-08-22 20:52
It makes me wonder if the fix didn't make it to the logic that parses through anonymous functions.  I was gonna spend a little time tonight finding that PR and seeing what it did where.

**Comment by Gotbread** [comment] 2016-08-24 05:29
I encountered a similar problem with anonymous functions. kuniverse:forceactive does not seem to work either:

![koserr3](https://cloud.githubusercontent.com/assets/19180639/17919269/7679f7d6-69cc-11e6-93e0-3203694d05ba.png)

**Comment by hvacengi** [comment] 2016-08-24 14:20
@Gotbread have you verified that the function works using a named function/delegate?  As it is a different error message and different circumstance it seems more likely that your error message is internal to the C#.  The original error was during program compilation, and was complaining about a missing dictionary key, while your error is while the program is actively running and is complaining about an array index.  If moving the logic into a named method doesn't fix the error, you should submit a new issue.  In either case, please provide your log files so that we can see the stack trace of the error.

**Comment by Gotbread** [comment] 2016-08-24 18:05
I will try to replicate this issue and test if a seperate function fixes it. However this problem occured very late in a +1hour mission so i could do much testing at the time of the post.

**Comment by Dunbaratu** [comment] 2016-09-09 16:11
Assigned it as a reminder for others not to work on it (the PR is already made).

**Closed** 2016-09-22 00:48 UTC
Labels: bug
