### ISSUE TITLE
Vary max IPU by Part.cfg

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2007] opened 2017-05-06 07:23 UTC
We now have the means to make the Parts differ in their electric charge and in their extra disk size mass/price cost, depending on their era, by just editing the Part.cfg file alone.

(Any time we put such a thing into a KSPField in KOSProcessor, we make it possible to set it in Part.cfg.)

The only piece really missing for us to be able to consider a re-balance of the parts now is the execution speed.  I propose we add a config field for the max IPU alllowed.  (Where lower-tech CPUs max out at a much slower rate than higher-tech CPUs.)

Then we'd have all the following things we could edit in the part.cfg files:

max IPU allowed.
base disk size (max is always 4x this)
diskSpaceCostFactor (Funds per disk byte).
diskSpaceMassFactor (Megagrams per disk byte).

I think that's all we would need to let us balance the different parts properly and have the old ones represent older clunkier (read, more mass per byte, slower execution) tech.

This issue is just for adding the *ability* to vary IPU per part (moving max IPU, min IPU, and default IPU to KSPfields).  Actually deciding on the proper values that should go there in the part.cfg files once that capacity exists would be a different issue.

**Comment by hvacengi** [comment] 2017-05-06 22:01
Isn't this a duplicate of #1385?  Also, I started work on this a while ago but never finished it.  You can see my original work in progress code from over a year ago here: https://github.com/hvacengi/KOS/tree/issue-1385-ipu_in_part_config

**Closed** 2017-05-06 23:42 UTC
Labels: duplicate, enhancement
