### ISSUE TITLE
"Require signal" work around is broken in newer versions of KSP

### ISSUE THREAD

**Issue by vikdotdev** [KSP-KOS/KOS#2166] opened 2017-11-09 17:48 UTC
Greetings. 

I've been playing around with kOS for a couple of days now,  until I stumbled into this issue - once the ship is out of signal range the engines won't fire. Steering and throttle adjustment works but not the engine. As soon as signal is available again the engine will fire.

Is that an intended behavior? Doesn't look like it is. Am I missing something? Curious for your suggestions. 

Attaching all the scripts and the ship file.
	
KSP version - 1.3.1.1891
kOS - version - 1.1.3.2
Ubuntu 16.04 LTS

[Script.zip](https://github.com/KSP-KOS/KOS/files/1458628/Script.zip)

**Comment by hvacengi** [comment] 2017-11-09 18:33
Without seeing your craft file/vessel I'm going to guess that you don't have a probe core installed.  KSP internally checks for vessel control when updating engine throttle in a different way from when other controls are set.  If the probe core is indeed missing, then the actual bug is that we successfully set any of the other controls when we shouldn't.  The kOS part does not serve as a control source like a probe core does.

If the issue is not fixed by adding a probe core (or a manned control pod) please let us know.  Make sure to include any other mods you may have installed.  But the fact that kOS is able to change the steering and the throttle setting and it is only the engines that don't respond tells me that the issue is somehow rooted in KSP not thinking you have any control over the vessel.

**Comment by boololo** [comment] 2017-11-09 18:46
The probe core is present, you can find .craft file in the attachment. 

Other mods installed : Kerbal Engineer, EnvironmentalVisualEnchancements, StockVisualEnchancements.

Oh, and btw CommNet option "Require signal to control" is on. I don't think it matters, right?

**Comment by hvacengi** [comment] 2017-11-09 18:49
> Oh, and btw CommNet option "Require signal to control" is on. I don't think it matters, right?

Well... sort of.  We have implemented a really ugly hack that is supposed to brute force KSP to think that you can control a vessel only during the throttle update timing.  It worked when I wrote it when CommNet originally came out, but it could very well have broken after one of the KSP updates.  If you turn off that setting does everything work properly again?

**Comment by boololo** [comment] 2017-11-09 19:10
Yup, it works that way. Thank you!

**Comment by hvacengi** [comment] 2017-11-09 19:15
Don't thank me yet.  My next task is to figure out why our hack isn't working anymore, and then see if I can get it working again.  I am going to edit this issue title and self assign it to see if I can come up with anything to help.

**Comment by Dunbaratu** [comment] 2017-12-23 00:03
Marked with milestone 1.1.4.0 because I *think* it's already fixed but wasn't tagged for closing, if I understand the exchange of messages correctly.

**Comment by hvacengi** [comment] 2017-12-23 03:46
Actually, I don't know that this was fixed so much as I gave him a work around that required disabling the "super hard mode" feature "require signal".  None of the other changes I made to address RT's errors should have had an effect on this issue.

I haven't had time to look into this, but I have had time to think about the implications.  Once could say that under a strict interpretation of the "require signal" setting it is correctly locking out engine control, since they disable all probe control without signal.  That being said, KSP has not stock concept of a programmed probe core, and so it's really outside of their design case.  Add on that they don't apply the same limitations to steering itself and you have an ambiguous situation.  Part of me wants to just say we don't support the "require signal" setting, but I know that there are some users who see kOS as a good way to get immersion and want to lock out those controls.  But you can get that same level of immersion by just keeping your hands off the keyboard, so... 

I think it depends on how involved the potential solution is.  If it's really complicated and fragile (and therefore a risk for breaking easily) I recommend we abandon support.  But if we can make a robust implementation that is minimally invasive I'm all for it.

**Closed** 2021-08-24 19:50 UTC
