### ISSUE TITLE
Unlock not working in trigger scope again

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#1151] opened 2015-09-04 21:42 UTC
It looks like #1048 is still an issue even after PR #1052.  Running the following test script seems to not unlock steering, ut, or throttle:
```
set done to false.
set test to false.
lock throttle to 1.
lock ut to time:seconds.
on ag1 {
    //verbose("ag1 -> set test to true").
    set test to true.
}
when test then {
    //verbose("test -> unlock steering and ut").
    unlock steering.
    unlock ut.
}
on ag2 {
    //verbose("ag2 -> lock steering to ship:facing").
    lock steering to ship:facing.
}
on ag3 {
    //verbose("ag3 -> unlock throttle").
    unlock throttle.
}
on ag4 {
    //verbose("ag4 -> set done to true").
    set done to true.
}
when ag5 then {
    //verbose("ag5 -> unlock steering").
    unlock steering.
}
until done {
    wait 1.
    print ut.
}
```
(`verbose` is a user function I define that outputs to hudtext, which I wanted to show to verify that I can observe the trigger itself is working).

In the previous issue, it was noted that `{ unlock throttle. }` did not work either, but it does work with the current code in the debug branch.

**Comment by Dunbaratu** [comment] 2015-09-06 12:14
Be aware when testing this, that your example script has a problem.  When you UNLOCK something that was previously only ever a LOCK and was never a normal vanilla variable, you are effectively de-defining the identifier (until you LOCK it again). 

Therefore this test script, after the ``unlock ut.`` statement starts working again with the PR, will throw an exception the next time the main loop tries to:
```
print ut.
```
after you hit action group 1.  This may seem broken, but it's sort of broken as intended.  The idea is that `ut` is no longer a valid identifier after it's been unlocked (remember it was never really a variable - it was a lock, which is really a short function with only one statement - a return statement).

If It's your goal to leave 'ut' behind as a normal variable, but one in which the value is stuck in place statically and stops being recalculated, you can do one of two things:

solution 1:  Change your  trigger to this:
```
when test then {
    //verbose("test -> unlock steering and ut").
    unlock steering.
    local remember_ut is ut. // add this line
    unlock ut.
    set ut to remember_ut.  // add this line
}
```

This replaces `ut` the function call with `ut` the variable, giving it the last value the function ut returned before it went away.

Solution 2: Just don't unlock it - keep it as a lock, but lock it to a new expression which is just a hardcoded copy of the prev value it had.
```
when test then {
    //verbose("test -> unlock steering and ut").
    unlock steering.
    set old_ut to ut.
    lock ut to old_ut.
}
```

**Comment by Dunbaratu** [comment] 2015-09-09 02:20
Please close when pr #1153 is merged.  (It didn't auto-associate because it's two issues with the same PR).

**Closed** 2015-09-13 03:34 UTC
