### ISSUE TITLE
Unable to clear screen vectors when variables containing them no longer exist.

### ISSUE THREAD

**Issue by kaufman-bryce** [KSP-KOS/KOS#917] opened 2015-04-28 00:38 UTC
Let's say you have a program that does, say, `LOCAL draw IS VECDRAWARGS(etc,etc).` If you you do not unset or hide those vectors before the program exits you loose access to them forever and they just stay on screen until you reload the scene.

I would like to suggest the following:
* Some command to clear all drawn vectors
* Clear all vectors when the computer looses power/reboots

**Comment by Dunbaratu** [comment] 2015-04-28 23:16
This used to work I think.  Variables that got orphaned, if they were of type vecdraw, hid the vector upon being orphaned.

I think that stopped working when closures were added, because the closure might keep the vecdraw open and un-orphaned when there's a lock somewhere in the same scope.

So, yeah I think this used to be working, but now needs a different solution, and the suggestions are good ways.

**Comment by Dunbaratu** [comment] 2015-05-08 06:02
ref to PR #970.

**Comment by Dunbaratu** [comment] 2015-05-08 06:08
Verified as I was fixing this that it was definitely caused by closures.

This code did not exhibit the problem:
```
function draw_it {
  local vd is vecdraw(V(0,0,0),up:vector*30, red, "up vector", 1, true).
  print "waiting a bit, then vecdraw should fall out of scope and go away.".
  wait 3.
}.

draw_it().
```
But then change the example in one small way, and the problem appeared:
```
function draw_it {
  lock some_dummy to 0. // <---- newly inserted line here ------------------
  local vd is vecdraw(V(0,0,0),up:vector*30, red, "up vector", 1, true).
  print "waiting a bit, then vecdraw should fall out of scope and go away.".
  wait 3.
}.

draw_it().
```
The fact that a lock existed in that scope causes the vd variable to never quite get demolished until that lock closure which holds it open is gone.

It may be possible to make lock closures more sophisticated by tracking a list of which local vars it visited during its expression, and only holding them open (like closures work in more sophisticated languages), but it's not as easy as it seems because of nesting and function calls - it might mention a function call that in turn needs a local variable, so a shallow check doesn't catch it.

But in the meantime, yes you can just call a new `clearvecdraws()` method now.

**Comment by Dunbaratu** [comment] 2015-05-10 06:59
Closing now that #917 got pulled.

**Closed by Dunbaratu** 2015-05-10 06:59 UTC
Labels: enhancement
