### ISSUE TITLE
With FAR installed SHIP:TERMVELOCITY puts infinity to the stack.

### ISSUE THREAD

**Issue by nuclearphoenixegg** [KSP-KOS/KOS#188] opened 2014-07-07 20:08 UTC
While the ship is in motion and in the atmosphere SHIP:TERMVELOCITY returns infinity. It doesn't do this without FAR installed.

**Comment by dcrockwell** [comment] 2015-03-11 08:37
+1 for FAR support in kOS. It is extremely popular to the point that it warrants special support.

Perhaps if there were just a way to get atmospheric density at sea level from KerboScript? Then there would be no special support needed and we could do our own calculations based upon this, scale height, and atmospheric height.

**Comment by Dunbaratu** [comment] 2015-03-11 14:54
-1 to FAR support in kOS.
In addition to my usual reasons that FAR is being a bad citizen when it breaks the API and demands that other mods change to do things its way, there's also the fact that we have no idea yet what to expect when KSP 1.0 changes the stock aero system.  Whatever that does is going to require a change anyway and maybe invalidate anything we do this close to its release.

**Comment by gillonba** [comment] 2015-03-11 15:04
Also -1 to FAR support.  I would be inclined to agree with dcrockwell based on FAR's popularity, with Squad reworking the aero model there is a good chance that FAR will soon become much less relevant in the near future.  If that is the case, effort spent supporting it will have been wasted effort that could have been better spent elsewhere

**Comment by dcrockwell** [comment] 2015-03-12 03:03
>  with Squad reworking the aero model there is a good chance that FAR will soon become much less relevant in the near future.

I was unaware. I think you're right. -1 FAR support.

**Comment by futrtrubl** [comment] 2015-03-12 04:44
I don't think FAR is going anywhere. While the stock aero system is becoming more intuitive it is still not nearly as realistic as FAR. For one I don't believe it changes drag due to mach effects. Also I don't think it sets a precedent as FAR is a huge change to the system so it really had to change the underlying behavior. So I think special support is warranted and I believe just a matter of getting the terminal velocity straight from FAR.

**Comment by erendrake** [comment] 2015-03-12 04:45
@futrtrubl I dont think FAR is going anywhere either but i would advise letting the smoke clear from the 1.0 release before we continue with this.

**Comment by ferram4** [comment] 2015-03-13 06:05
I fail to see how FAR is being a bad citizen by breaking a non-existent API; it's not like there's a "vesselDrag" parameter that I can set.  In fact, it doesn't falsify the data at all; you're calculating the terminal velocity based on the drag of the stock massdrag system and getting the expected result when that is disabled with FAR.

I have the option of trying to provide support by applying drag forces *through* the massdrag system, but given that it adds a fair bit more calculations to apply forces I question whether the overhead is necessary.

I will also note that even attempting that will result in unintended behavior in FAR when handling physicsless (massless) parts that shouldn't be; this means that taking steps to make FAR compatible with the massdrag-assuming scheme you're using will result in parts like the 3.75m decoupler having no drag forces whatsoever.  Obviously that's bad, so the next step would be to attempt to apply forces to the nearest physics-having part, but adjust things to keep it behaving properly.

So I don't know what you guys want me to do short of filling FAR with workarounds.  I can add any function you guys want to make interfacing easier, but trying to fix it by fitting FAR into the massdrag assumptions that you're working on will inevitably cause bugs / require convoluted workarounds in FAR.

**Comment by Dunbaratu** [comment] 2015-03-13 07:35
Keep in mind that the bug report here wasn't "Installing FAR caused the stock terminal velocity value to be wrong" - THAT would be expected, and fine.  The bug report here is that installing FAR made the script crash when FAR altered the numbers used in the stock calculation.

That's where I'm coming from.  I'm not talking about trying to make an exception to return FAR's values - just about keeping FAR's changes to the stock values from crashing our math.

Solving it generically for all mods (treating them like equal citizens and not giving special status to FAR) is nearly impossible due to the the fact that the generic solution is to say that we can never assume anything about any properties or fields coming from the KSP API that are used in a formula.  ANY of them could be falsified by another mod, so protect against potential bogus values for *all* of them.  <-- that would be unworkably messy.

Thus my claim that fixing this means giving special exceptions to FAR, and I don't feel comfortable with having to do that, but I can see I'm getting outvoted on that.

Hopefully 1.0 will allow a cleaner way for you to tell the stock aero system to disable itself that won't involve having to falsify the stock fields on parts (setting drag coefficients to zero) to do it.   If that happens then the entire problem will be moot anyway.  We'll have to wait and see what 1.0 does.

@erendrake, There's a place in our code where an Infinity is being *deliberately* put on the stack to report an error condition back to the script, file KOS/Utilities/VesselUtils.cs, line 359.  That should be changed to a maxdouble instead.  I don't know how old that code is but I suspect it predates marianoapp's stack-forbids-infinity change from ages ago.

**Comment by hvacengi** [comment] 2015-06-06 05:22
As we have deprecated the suffix TERMINALVELOCITY, I'd say that the original "bug" is at least gone.  Do we want to continue this discussion as an attempt to access the data from FAR directly?

**Comment by blnk2007** [comment] 2015-06-30 04:05
Looks like FAR is still relevant.

**Comment by dcrockwell** [comment] 2015-06-30 04:06
Indeed ;)

**Comment by Dunbaratu** [comment] 2015-06-30 21:56
The claim was never "far will be irrelevant", but that supporting the old FAR code would be irrelevant because it cannot stay the same and still be compatible with 1.0.  The FAR code had to have a major overhaul - anything we did to support what it was doing pre-1.0 would have been wasted effort to throw away and start over.  Post-1.0 FAR is not the same animal as pre-1.0 FAR was.

**Comment by blnk2007** [comment] 2015-07-01 15:58
What's the status on this now?

**Comment by erendrake** [comment] 2015-07-01 16:13
@blnk2007 As far as i know. "Terminal velocity" is not a very useful stat for either stock or FAR. Which is why i deprecated it. I have seen quite a few people asking for a dynamic pressure binding but i dont have the maths on hand to add it.

**Comment by sarbian** [comment] 2015-07-01 16:17
vessel.dynamicPressurekPa * 1000 ?

**Comment by erendrake** [comment] 2015-07-01 16:19
@sarbian perfect :) I havent spent very much quality time with the stock aero part of the API so i didnt know we had that available. Thank you!

**Comment by blnk2007** [comment] 2015-07-01 16:52
Awesome! Now if only MechJeb could add this! it could be used instead of "Limit Terminal Velocity". Maybe?

**Comment by hvacengi** [comment] 2015-12-01 23:35
Since this was converted into the dynamic pressure suffix, and terminal velocity itself has been abandoned, I'm going to close this issue.  We can reopen it if more discussion is required.

**Closed by hvacengi** 2015-12-01 23:35 UTC
Labels: enhancement
